# ══════════════════════════════════════════════════════════════════════════════
# SECTION 1: HEADER
# ══════════════════════════════════════════════════════════════════════════════
#
# Estimates key migration dates for Atlantic salmon post-smolts from two river
# systems (Saint Jean and Trinite) using acoustic telemetry detection data.
# Computes least-cost swimming distances between receiver stations and derives
# a mean swimming speed, which is then used to define migration windows across
# the Strait of Belle Isle, southern Labrador, and the Labrador Sea.
#
# Inputs:
#   - R/00_raw_data/telemetry/master_dataset_smolt_manuscript_dec_10_2025 QC.csv
#       Acoustic telemetry detection data (CSV, semicolon-separated, comma decimal)
#       Confidential — see DATA IMPORT section for access instructions.
#   - R/00_derived_data/Year_Median_Date_StJean.fst
#       Median smolting date by year for Saint Jean River (FST format)
#       Generated by running: 01_SmoltingDates_StJean.R
#   - R/00_derived_data/Year_Median_Date_Trinite.fst
#       Median smolting date by year for Trinite River (FST format)
#       Generated by running: 01_SmoltingDates_Trinite.R
#
# Outputs:
#   - R/00_derived_data/Year_Migration_Dates_River_Sea.fst
#       Migration date windows by river and cohort year (FST format)
#   - 02_PrepareData_Scripts/SST/MigrationDates_Distributions_FINAL.pdf
#       PDF figure showing receiver station map and migration date distributions
# ══════════════════════════════════════════════════════════════════════════════




# ══════════════════════════════════════════════════════════════════════════════
# SECTION 2: LIBRARIES
# ══════════════════════════════════════════════════════════════════════════════

library(dplyr)
library(lubridate)
library(ggplot2)
library(sf)
library(rnaturalearth)
library(rnaturalearthdata)
library(terra)
library(raster)
library(gdistance)
library(reshape2)
library(purrr)
library(fst)




# ══════════════════════════════════════════════════════════════════════════════
# SECTION 3: WORKING DIRECTORY
# ══════════════════════════════════════════════════════════════════════════════

# ── Working directory ──────────────────────────────────────────────────────
# Automatically detects the repository root based on the script location.
# No hardcoded path — works on any machine.
current_file <- rstudioapi::getActiveDocumentContext()$path
path_parts   <- unlist(strsplit(normalizePath(current_file, winslash = "/"), "/"))
target_index <- which(path_parts == "phd-chapter3-Atlantic-Salmon")
base_path    <- paste(path_parts[1:target_index], collapse = "/")
setwd(base_path)




# ══════════════════════════════════════════════════════════════════════════════
# SECTION 4: DATA IMPORT
# ══════════════════════════════════════════════════════════════════════════════

# ── Telemetry data ─────────────────────────────────────────────────────────
# SOURCE: Lilly et al. (unpublished manuscript, under review).
# STATUS: Confidential — not included in this repository.
#         This file is a subset of the authors' full telemetry dataset.
#         An example file with identical structure and simulated data is
#         available at the same path with the suffix _EXAMPLE.csv.
#         To request access to the full dataset, contact the authors directly
#         once the manuscript has been published.
#
# To run with example data, replace the filename below with:
#   "master_dataset_smolt_manuscript_EXAMPLE.csv"

tel <- read.csv(
  file   = file.path(base_path, "R/00_raw_data/telemetry/master_dataset_smolt_manuscript_dec_10_2025 QC.csv"),
  sep    = ";",
  dec    = ",",
  header = TRUE
)




# ══════════════════════════════════════════════════════════════════════════════
# SECTION 7: MAIN SCRIPT
# ══════════════════════════════════════════════════════════════════════════════

# ── Plot receiver stations ──────────────────────────────────────────────────

# Load coastlines for mapping
coastline <- ne_coastline(scale = "large", returnclass = "sf")

# Retain only stations belonging to the target geographic areas
stations <- tel %>%
  dplyr::distinct(Station_Name, Latitude, Longitude, Location) %>%
  dplyr::filter(Location %in% c(
    "gulf_of_st_lawrence_1", "strait_of_belle_isle",
    "st_anthony", "southern_labrador", "newfoundland_1"
  ))

stations_sf <- st_as_sf(
  stations,
  coords = c("Longitude", "Latitude"),
  crs    = 4326   # WGS84
)

# Define map extent
bbox <- st_bbox(c(
  xmin = -59, xmax = -54,
  ymin = 50,  ymax = 53
), crs = st_crs(4326))

# Map of receiver stations colored by location
map <- ggplot() +
  geom_sf(data = coastline, color = "grey40", linewidth = 0.3) +
  geom_sf(data = stations_sf, size = 2, aes(color = Location)) +
  coord_sf(
    xlim   = c(bbox["xmin"], bbox["xmax"]),
    ylim   = c(bbox["ymin"], bbox["ymax"]),
    expand = FALSE
  ) +
  scale_color_discrete(
    labels = c(
      gulf_of_st_lawrence_1 = "Gulf of St. Lawrence",
      strait_of_belle_isle  = "Strait of Belle Isle (SOBI)",
      st_anthony            = "St-Anthony (STAN)",
      southern_labrador     = "Southern Labrador (SLAB)",
      newfoundland_1        = "Newfoundland 1"
    )
  ) +
  labs(x = "Longitude", y = "Latitude") +
  theme_minimal(base_size = 13)

map


# ── Standardize and deduplicate telemetry data ─────────────────────────────

tel <- tel %>%
  # Harmonize column names for downstream consistency
  dplyr::rename(
    id           = serialno_tag,
    date_hit     = Date_Hit,
    hit_location = Location,
    origin_river = river
  ) %>%
  # Retain one detection per individual per day to avoid pseudo-replication
  dplyr::group_by(id, date_hit) %>%
  dplyr::slice(1) %>%
  dplyr::ungroup() %>%
  dplyr::mutate(date_hit = as.Date(date_hit))


# ── Arrival date at SOBI (Strait of Belle Isle) ────────────────────────────
#
# Only the FIRST detection at SOBI (or at the preceding Gulf array) per
# individual per deployment year is kept. This date serves as the entry
# date into SOBI and is used to quantify time spent in the Gulf of
# St. Lawrence. If an individual was detected at both arrays, the SOBI
# detection takes priority over the Gulf array detection.

# Saint Jean River (and Restigouche, Cascapedia)
tel_first_obs_stj <- tel %>%
  dplyr::filter(
    Latitude >= 50.5,
    hit_location %in% c("strait_of_belle_isle", "gulf_of_st_lawrence_1"),
    origin_river %in% c("Restigouche River", "Cascapedia River", "Saint Jean River")
  ) %>%
  dplyr::mutate(date_hit = as.Date(date_hit)) %>%
  # First detection per individual x river x location x year
  dplyr::group_by(id, deploy_year, origin_river, hit_location) %>%
  dplyr::slice_min(date_hit, n = 1, with_ties = FALSE) %>%
  dplyr::ungroup() %>%
  # If SOBI detection exists for this individual x year, drop the Gulf entry
  dplyr::group_by(id, deploy_year) %>%
  dplyr::filter(
    !(any(hit_location == "strait_of_belle_isle") &
        hit_location == "gulf_of_st_lawrence_1")
  ) %>%
  dplyr::ungroup() %>%
  dplyr::select(id, date_hit, origin_river, hit_location, deploy_year)

nrow(tel_first_obs_stj)

# Sample size per river and detection location
tel_first_obs_stj %>%
  dplyr::group_by(origin_river, hit_location) %>%
  dplyr::summarise(n = length(hit_location))

# Aggregate to daily counts (day-of-year) for computing the detection distribution
sobi_daily_detections_stj <- tel_first_obs_stj %>%
  dplyr::mutate(
    year = deploy_year,
    doy  = yday(date_hit)
  ) %>%
  count(year, doy, name = "n_detections")


# Trinite River (and Saguenay)
tel_first_obs_tri <- tel %>%
  dplyr::filter(
    Latitude >= 50.5,
    hit_location %in% c("strait_of_belle_isle", "gulf_of_st_lawrence_1"),
    origin_river %in% c("Trinite River", "Saguenay River")
  ) %>%
  dplyr::mutate(date_hit = as.Date(date_hit)) %>%
  dplyr::group_by(id, deploy_year, origin_river, hit_location) %>%
  dplyr::slice_min(date_hit, n = 1, with_ties = FALSE) %>%
  dplyr::ungroup() %>%
  dplyr::group_by(id, deploy_year) %>%
  dplyr::filter(
    !(any(hit_location == "strait_of_belle_isle") &
        hit_location == "gulf_of_st_lawrence_1")
  ) %>%
  dplyr::ungroup() %>%
  dplyr::select(id, date_hit, origin_river, hit_location, deploy_year)

nrow(tel_first_obs_tri)

tel_first_obs_tri %>%
  dplyr::group_by(origin_river, hit_location) %>%
  dplyr::summarise(n = length(hit_location))

sobi_daily_detections_tri <- tel_first_obs_tri %>%
  dplyr::mutate(
    year = deploy_year,
    doy  = yday(date_hit)
  ) %>%
  count(year, doy, name = "n_detections")


# Median and standard deviation of SOBI entry day-of-year per river group
sobi_arrival_stj_median_sd <- data.frame(
  median_detection = median(sobi_daily_detections_stj$doy),
  sd_detection     = sd(sobi_daily_detections_stj$doy)
)

sobi_arrival_tri_median_sd <- data.frame(
  median_detection = median(sobi_daily_detections_tri$doy),
  sd_detection     = sd(sobi_daily_detections_tri$doy)
)


# ── Exit date from SOBI / entry into the Labrador Sea ──────────────────────
#
# Only the LAST detection at the southern Labrador / Newfoundland arrays per
# individual per year is retained. This date approximates the moment fish
# leave SOBI and enter the Labrador Sea. A priority order is applied when
# detections exist at multiple downstream arrays: southern Labrador >
# Newfoundland 1 > St-Anthony.
#
# The resulting distribution is used to define the SOBI exit date:
# 75th percentile for Saint Jean fish and 95th percentile for Trinite fish,
# because sample sizes are small for the latter and the distributions overlap.

# Saint Jean River (and Restigouche, Cascapedia)
tel_last_obs_stj <- tel %>%
  dplyr::filter(
    Latitude >= 50.5,
    hit_location %in% c("southern_labrador", "newfoundland_1", "st_anthony"),
    origin_river %in% c("Restigouche River", "Cascapedia River", "Saint Jean River")
  ) %>%
  dplyr::mutate(date_hit = as.Date(date_hit)) %>%
  # Last detection per individual x river x location x year
  dplyr::group_by(id, deploy_year, origin_river, hit_location) %>%
  dplyr::slice_max(date_hit, n = 1, with_ties = FALSE) %>%
  dplyr::ungroup() %>%
  # Assign priority: southern_labrador > newfoundland_1 > st_anthony
  dplyr::mutate(
    priority = dplyr::case_when(
      hit_location == "southern_labrador" ~ 1,
      hit_location == "newfoundland_1"    ~ 2,
      hit_location == "st_anthony"        ~ 3
    )
  ) %>%
  # Retain the highest-priority detection per individual x year
  dplyr::group_by(id, deploy_year) %>%
  dplyr::slice_min(priority, n = 1, with_ties = FALSE) %>%
  dplyr::ungroup() %>%
  dplyr::select(id, date_hit, origin_river, hit_location, deploy_year)

nrow(tel_last_obs_stj)

stan_slab_daily_detections_stj <- tel_last_obs_stj %>%
  dplyr::mutate(
    year = deploy_year,
    doy  = yday(date_hit)
  ) %>%
  count(year, doy, name = "n_detections")


# Trinite River (and Saguenay)
tel_last_obs_tri <- tel %>%
  dplyr::filter(
    Latitude >= 50.5,
    hit_location %in% c("southern_labrador", "newfoundland_1", "st_anthony"),
    origin_river %in% c("Trinite River", "Saguenay River")
  ) %>%
  dplyr::mutate(date_hit = as.Date(date_hit)) %>%
  dplyr::group_by(id, deploy_year, origin_river, hit_location) %>%
  dplyr::slice_max(date_hit, n = 1, with_ties = FALSE) %>%
  dplyr::ungroup() %>%
  dplyr::mutate(
    priority = dplyr::case_when(
      hit_location == "southern_labrador" ~ 1,
      hit_location == "newfoundland_1"    ~ 2,
      hit_location == "st_anthony"        ~ 3
    )
  ) %>%
  dplyr::group_by(id, deploy_year) %>%
  dplyr::slice_min(priority, n = 1, with_ties = FALSE) %>%
  dplyr::ungroup() %>%
  dplyr::select(id, date_hit, origin_river, hit_location, deploy_year)

nrow(tel_last_obs_tri)

stan_slab_daily_detections_tri <- tel_last_obs_tri %>%
  dplyr::mutate(
    year = deploy_year,
    doy  = yday(date_hit)
  ) %>%
  count(year, doy, name = "n_detections")


# Median and standard deviation of downstream exit day-of-year
# (pooled across both river groups, as distributions overlap)
stan_slab_daily_detections_both <- rbind(
  stan_slab_daily_detections_stj,
  stan_slab_daily_detections_tri
)

stan_slab_arrival_stj_median_sd <- data.frame(
  median_detection = median(stan_slab_daily_detections_both$doy),
  sd_detection     = sd(stan_slab_daily_detections_both$doy)
)

stan_slab_arrival_tri_median_sd <- data.frame(
  median_detection = median(stan_slab_daily_detections_both$doy),
  sd_detection     = sd(stan_slab_daily_detections_both$doy)
)


# ── Summary table of migration dates ──────────────────────────────────────

dates_final <- data.frame(
  river       = c("stj", "stj", "tri", "tri"),
  arriving_to = c("sobi", "lab", "sobi", "lab"),
  date_doy = c(
    round(sobi_arrival_stj_median_sd$median_detection),
    round(stan_slab_arrival_stj_median_sd$median_detection),
    round(sobi_arrival_tri_median_sd$median_detection),
    round(stan_slab_arrival_tri_median_sd$median_detection)
  ),
  sd_date = c(
    round(sobi_arrival_stj_median_sd$sd_detection),
    round(stan_slab_arrival_stj_median_sd$sd_detection),
    round(sobi_arrival_tri_median_sd$sd_detection),
    round(stan_slab_arrival_tri_median_sd$sd_detection)
  )
) %>%
  dplyr::mutate(date = format(as.Date(date_doy - 1, origin = "2001-01-01"), "%m-%d"))


# ── Export distribution plots to PDF ──────────────────────────────────────

ggplot(
  dates_final,
  aes(
    x     = date_doy,
    y     = river,
    color = factor(arriving_to, levels = c("sobi", "lab"))
  )
) +
  geom_point(position = position_dodge(width = 0.4), size = 3) +
  geom_errorbarh(
    aes(xmin = date_doy - sd_date, xmax = date_doy + sd_date),
    position  = position_dodge(width = 0.4),
    height    = 0.15,
    linewidth = 1
  ) +
  geom_text(
    aes(label = format(as.Date(date_doy - 1, origin = "2001-01-01"), "%m-%d")),
    position   = position_dodge(width = 0.4),
    vjust      = -1.2,
    size       = 3.5,
    show.legend = FALSE
  ) +
  geom_text(
    aes(label = paste0("+-", sd_date, " days")),
    position   = position_dodge(width = 0.4),
    vjust      = 1.8,
    size       = 3,
    show.legend = FALSE
  ) +
  scale_y_discrete(labels = c(stj = "St. Jean", tri = "Trinite")) +
  scale_x_continuous(
    name   = "Date",
    limits = c(170, 240),
    breaks = seq(170, 240, by = 10),
    labels = function(x) format(as.Date(x - 1, origin = "2001-01-01"), "%m-%d")
  ) +
  labs(y = NULL, color = "Arriving at:") +
  scale_color_discrete(labels = c(sobi = "SOBI", lab = "Labrador\nSea")) +
  theme_minimal(base_size = 18)



# ── Post-smolt swimming speed from telemetry and literature ────────────────
#
# Literature estimates of Atlantic salmon post-smolt swimming speeds generally
# fall within approximately 14 to 22 km/d. Studies conducted in the Gulf of
# St. Lawrence during the early marine phase, shortly after river exit, report
# mean speeds of ~14-18 km/d (Lefevre et al. 2012) and ~17-22 km/d (Chaput
# et al. 2019). Similar values have been reported elsewhere in the North
# Atlantic, including the Faroe-Shetland Channel, where post-smolts covered
# 713-874 km in 38-51 days (14-21 km/d; Shelton et al. 1997). Observations
# from more offshore or later migration stages indicate comparable or slightly
# higher values, with mean speeds around 22 km/d reported in the Northeast
# Atlantic (Holst et al. 1996) and in the Labrador Sea (Reddin & Short 1991).
#
# It is important to note that many of these estimates are derived from fish
# in the first phase of their marine migration, often shortly after river exit,
# when individuals are smaller and may exhibit lower sustained swimming speeds.
# In contrast, our estimate of a mean swimming speed of approximately 23 km/d
# is based on fish originating from the same river systems and observed farther
# along their migration, in the Strait of Belle Isle region. At this stage,
# individuals are expected to be slightly larger and more developmentally
# advanced, which is expected to translate into higher swimming capacity.
# Consequently, although our estimate lies at the upper end of the range
# reported in the literature, it remains biologically plausible and consistent
# with existing studies when differences in fish size and migration stage are
# taken into account.
#
# Thus, considering that the polygon at the entrance to the Labrador Sea is
# 300 km wide, we estimate that it will take (300 km) / (23 km/day) = 13 days
# to cross this polygon.
#
# | Source               | Distance / Time              | Average speed     |
# | -------------------- | ---------------------------- | ----------------- |
# | Lefevre et al. 2012  | ~630-800 km in 44 d          | ~14.4-18.2 km/d   |
# | Chaput et al. 2019   | ~800 km in ~36-48 d          | ~17-22 km/d       |
# | Shelton et al. 1997  | 713-874 km in 38-51 d        | 14-21 km/d        |
# | Holst et al. 1996    | ~2000 km                     | ~22 km/d          |
# | Reddin & Short, 1991 |                              | ~22 km/d          |
#
# References:
# Lefevre, M. A., Stokesbury, M. J., Whoriskey, F. G., & Dadswell, M. J.
#   (2012). Atlantic salmon post-smolt migration routes in the Gulf of
#   St. Lawrence. ICES Journal of Marine Science, 69(6), 981-990.
# Chaput, G., Carr, J., Daniels, J., Tinker, S., Jonsen, I., & Whoriskey, F.
#   (2019). Atlantic salmon (Salmo salar) smolt and early post-smolt migration
#   and survival inferred from multi-year and multi-stock acoustic telemetry
#   studies in the Gulf of St. Lawrence, northwest Atlantic. ICES Journal of
#   Marine Science, 76(4), 1107-1121.
# Shelton, R. G. J., Turrell, W. R., Macdonald, A., McLaren, I. S., & Nicoll,
#   N. T. (1997). Records of post-smolt Atlantic salmon, Salmo salar L., in
#   the Faroe-Shetland Channel in June 1996. Fisheries Research,
#   31(1-2), 159-162.
# Holst, J. C., Hansen, L. P., & Holm, M. (1996). Observations of abundance,
#   stock composition, body size and food of postsmolts of Atlantic salmon in
#   the NE Atlantic during summer.
# Reddin, D. G., & Short, P. B. (1991). Postsmolt Atlantic salmon (Salmo
#   salar) in the Labrador Sea. Canadian Journal of Fisheries and Aquatic
#   Sciences, 48(1), 2-6.


# ── Build paired entry-exit dataset for SOBI ──────────────────────────────

# Retain the entry-side detections (SOBI or Gulf array)
tel_entry_sobi <- tel %>%
  dplyr::filter(hit_location %in% c("gulf_of_st_lawrence_1", "strait_of_belle_isle")) %>%
  dplyr::rename(
    hit_location_entry = hit_location,
    date_hit_entry     = date_hit,
    SerialNo_Rec_entry = SerialNo_Rec,
    Station_Name_entry = Station_Name,
    Latitude_entry     = Latitude,
    Longitude_entry    = Longitude
  ) %>%
  dplyr::select(
    id, origin_river, hit_location_entry, date_hit_entry,
    SerialNo_Rec_entry, Station_Name_entry, Latitude_entry,
    Longitude_entry, fl_mm
  )

# Retain the exit-side detections (southern Labrador, Newfoundland, St-Anthony)
tel_exit_sobi <- tel %>%
  dplyr::filter(hit_location %in% c("newfoundland_1", "southern_labrador", "st_anthony")) %>%
  dplyr::rename(
    hit_location_exit = hit_location,
    date_hit_exit     = date_hit,
    SerialNo_Rec_exit = SerialNo_Rec,
    Station_Name_exit = Station_Name,
    Latitude_exit     = Latitude,
    Longitude_exit    = Longitude
  ) %>%
  dplyr::select(
    id, origin_river, hit_location_exit, date_hit_exit,
    SerialNo_Rec_exit, Station_Name_exit, Latitude_exit,
    Longitude_exit, fl_mm
  )

# Match each individual's entry with its corresponding exit
tel_distances_sobi <- merge(tel_entry_sobi, tel_exit_sobi, by = c("id", "origin_river"))


# ── Compute least-cost distances between receiver stations ────────────────
#
# Least-cost path distances are computed through water only (land = NA),
# which prevents straight-line paths from cutting across land masses.
# A 0.001-degree resolution raster is used to balance accuracy and
# computation time. The transition surface is corrected for geographic
# distance using geoCorrection() so that costDistance() returns meters.

# Extract unique station coordinates within the target region
station_distances <- tel %>%
  dplyr::select(SerialNo_Rec, Station_Name, Latitude, Longitude, hit_location)

stations_sf <- station_distances %>%
  dplyr::filter(
    Latitude >= 50.5,
    hit_location %in% c(
      "gulf_of_st_lawrence_1", "strait_of_belle_isle",
      "newfoundland_1", "southern_labrador", "st_anthony"
    )
  ) %>%
  distinct(SerialNo_Rec, Latitude, Longitude, hit_location) %>%
  st_as_sf(coords = c("Longitude", "Latitude"), crs = 4326)

# Load country polygons for land masking
land <- ne_countries(scale = "large", returnclass = "sf")

ggplot() +
  geom_sf(data = land) +
  geom_sf(data = stations_sf, aes(color = hit_location)) +
  coord_sf(
    xlim   = c(bbox["xmin"] - 10, bbox["xmax"] + 2),
    ylim   = c(bbox["ymin"] - 5,  bbox["ymax"]),
    expand = FALSE
  )

# Build a cost raster: water = 1, land = NA (impassable)
ext    <- ext(stations_sf) + 0.1  # Extend to include all station areas
r      <- rast(extent = ext, resolution = 0.001, crs = "EPSG:4326")
values(r) <- 1                    # Initialize all cells as water
r_land <- rasterize(vect(land), r, field = 1)
r[r_land == 1] <- NA              # Land cells are impassable

plot(r)
plot(st_geometry(stations_sf), add = TRUE, pch = 16, col = "red", cex = 0.7)

# Reproject to UTM zone 20N (meters) for distance calculations
stations_sf <- st_transform(stations_sf, 32620)
land        <- st_transform(land, 32620)

# Convert to RasterLayer (required by gdistance::transition())
r_raster <- raster(r)
r_raster <- projectRaster(r_raster, crs = 32620, method = "bilinear")

# Build the transition surface (8-direction movement) and apply geographic correction
tr <- transition(r_raster, function(x) 1 / mean(x), 8)
tr <- geoCorrection(tr, type = "c")

# Compute the full pairwise least-cost distance matrix (in meters)
dist_mat_m <- costDistance(
  tr,
  st_coordinates(stations_sf),
  st_coordinates(stations_sf)
)

# Reshape distance matrix to long format for joining to individual data
ids               <- stations_sf$SerialNo_Rec
rownames(dist_mat_m) <- ids
colnames(dist_mat_m) <- ids

dist_long <- reshape2::melt(
  dist_mat_m,
  varnames   = c("SerialNo_Rec_entry", "SerialNo_Rec_exit"),
  value.name = "distance_m"
)


# ── Compute travel time and swimming speed per individual ─────────────────

# Join distances to paired entry-exit records
distances_id <- merge(
  tel_distances_sobi, dist_long,
  by = c("SerialNo_Rec_entry", "SerialNo_Rec_exit")
) %>%
  dplyr::mutate(distance_km = distance_m / 1000) %>%
  dplyr::select(-distance_m)

distances_id <- distances_id %>%
  dplyr::select(
    id, origin_river, SerialNo_Rec_entry, SerialNo_Rec_exit,
    hit_location_entry, hit_location_exit, date_hit_entry,
    date_hit_exit, distance_km, fl_mm.y
  ) %>%
  dplyr::mutate(
    date_hit_entry = yday(date_hit_entry),
    date_hit_exit  = yday(date_hit_exit),
    travel_time    = date_hit_exit - date_hit_entry
  ) %>%
  # When entry is detected at both arrays, give priority to SOBI over the Gulf array
  group_by(id, SerialNo_Rec_exit) %>%
  slice_min(
    order_by = if_else(hit_location_entry == "strait_of_belle_isle", 0, 1),
    n = 1
  ) %>%
  ungroup() %>%
  # Remove cases where exit was detected before or on the same day as entry
  filter(travel_time > 0) %>%
  dplyr::mutate(
    swim_speed = distance_km / travel_time,
    region     = ifelse(
      origin_river %in% c("Restigouche River", "Cascapedia River", "Saint Jean River"),
      "Gaspesie", "North Shore"
    )
  )

# Mean swimming speed used to estimate transit time across the Labrador Sea polygon
mean_swim_speed <- round(mean(distances_id$swim_speed))  # km / day
round(300 / mean_swim_speed)                              # days to cross 300 km polygon


# ── Plot least-cost migration routes ──────────────────────────────────────

# Prepare projected station coordinates for route visualization
stations_proj <- station_distances %>%
  distinct(SerialNo_Rec, Station_Name, Latitude, Longitude) %>%
  st_as_sf(coords = c("Longitude", "Latitude"), crs = 4326) %>%
  st_transform(32620)

# Build table of unique entry-exit pairs to compute paths for
pairs <- distances_id %>%
  distinct(id, SerialNo_Rec_entry, SerialNo_Rec_exit, origin_river)


# ── Functions ──────────────────────────────────────────────────────────────

# get_path
# Purpose: Computes the shortest water path between two receiver stations
#          using the pre-built least-cost transition surface.
# Parameters:
#   entry   - SerialNo_Rec identifier for the entry station
#   exit    - SerialNo_Rec identifier for the exit station
#   fish_id - Individual fish identifier (id column)
#   river   - River of origin for the fish
# Returns: An sf LINESTRING object with the shortest path, or NULL if
#          either station is missing from stations_proj.
get_path <- function(entry, exit, fish_id, river) {
  
  start_pt <- stations_proj %>% filter(SerialNo_Rec == entry)
  end_pt   <- stations_proj %>% filter(SerialNo_Rec == exit)
  
  if (nrow(start_pt) == 0 | nrow(end_pt) == 0) return(NULL)
  
  path_sp <- shortestPath(
    tr,
    st_coordinates(start_pt),
    st_coordinates(end_pt),
    output = "SpatialLines"
  )
  
  proj4string(path_sp) <- CRS("+proj=utm +zone=20 +datum=WGS84 +units=m +no_defs")
  
  path_sf       <- st_as_sf(path_sp)
  path_sf$id    <- fish_id
  path_sf$river <- river
  path_sf$entry <- entry
  path_sf$exit  <- exit
  
  return(path_sf)
}

# Compute all individual migration paths
paths_list <- pmap(
  list(
    pairs$SerialNo_Rec_entry,
    pairs$SerialNo_Rec_exit,
    pairs$id,
    pairs$origin_river
  ),
  get_path
)

paths_sf <- do.call(rbind, paths_list)

# Define map bounds in geographic and projected coordinates
bbox_ll <- st_bbox(c(
  xmin = -59, xmax = -54,
  ymin = 50,  ymax = 53
), crs = st_crs(4326))

bbox_utm  <- st_transform(st_as_sfc(bbox_ll), 32620) %>% st_bbox()
land_utm  <- st_transform(land, 32620)

ggplot() +
  geom_sf(data = land_utm, fill = "white", color = "grey50", linewidth = 0.4) +
  geom_sf(data = paths_sf, linewidth = 0.8, alpha = 0.6) +
  geom_sf(data = stations_proj, color = "RED", size = 1.5) +
  coord_sf(
    xlim   = c(bbox_utm["xmin"], bbox_utm["xmax"]),
    ylim   = c(bbox_utm["ymin"], bbox_utm["ymax"]),
    expand = FALSE
  ) +
  labs(x = "Longitude", y = "Latitude") +
  theme_minimal(base_size = 13) +
  theme(
    panel.background = element_rect(fill = "white", color = NA),
    plot.background  = element_rect(fill = "white", color = NA)
  )


# ── Define Labrador Sea exit dates ────────────────────────────────────────
#
# According to Imlay et al. (2024), the summer period for post-smolts spans
# August to November during their first year at sea, and May to November
# during their second year; the winter period spans December to April in
# both years. May 1st is therefore used as the Labrador Sea exit date for
# both 1SW and 2SW fish.

lab_sea_1sw_exit <- yday(as.Date("2001-05-01"))
lab_sea_2sw_exit <- yday(as.Date("2001-05-01"))


# ── Assemble final migration date dataset ─────────────────────────────────

# Sea migration windows by river and cohort year
all_dates_sea <- bind_rows(
  data.frame(
    river                  = "stj",
    cohort                 = 1980:2025,
    sobi_entry             = as.numeric(round(sobi_arrival_stj_median_sd$median_detection)),
    sobi_exit              = round(stan_slab_arrival_stj_median_sd$median_detection),
    entering_lab_sea_entry = as.numeric(round(stan_slab_arrival_stj_median_sd$median_detection)),
    entering_lab_sea_exit  = as.numeric(round(stan_slab_arrival_stj_median_sd$median_detection)) +
      round(300 / as.numeric(mean_swim_speed)),
    lab_sea_entry          = as.numeric(round(stan_slab_arrival_stj_median_sd$median_detection)),
    lab_sea_exit_1sw       = lab_sea_1sw_exit,
    lab_sea_exit_2sw       = lab_sea_2sw_exit
  ),
  data.frame(
    river                  = "tri",
    cohort                 = 1980:2025,
    sobi_entry             = as.numeric(round(sobi_arrival_tri_median_sd$median_detection)),
    sobi_exit              = as.numeric(round(stan_slab_arrival_tri_median_sd$median_detection)),
    entering_lab_sea_entry = as.numeric(round(stan_slab_arrival_tri_median_sd$median_detection)),
    entering_lab_sea_exit  = as.numeric(round(stan_slab_arrival_tri_median_sd$median_detection)) +
      round(300 / as.numeric(mean_swim_speed)),
    lab_sea_entry          = as.numeric(round(stan_slab_arrival_tri_median_sd$median_detection)),
    lab_sea_exit_1sw       = lab_sea_1sw_exit,
    lab_sea_exit_2sw       = lab_sea_2sw_exit
  )
)

# Smolting dates by river and cohort year
all_dates_smolt <- bind_rows(
  read_fst("R/00_derived_data/Year_Median_Date_StJean.fst"),
  read_fst("R/00_derived_data/Year_Median_Date_Trinite.fst")
) %>%
  dplyr::select(river, cohort, median_date_doy, quantile_25_date, quantile_75_date) %>%
  dplyr::rename(
    smolting_doy       = median_date_doy,
    smolt_quant_25_doy = quantile_25_date,
    smolt_quant_75_doy = quantile_75_date
  ) %>%
  dplyr::mutate(
    smolt_quant_25_doy = yday(smolt_quant_25_doy),
    smolt_quant_75_doy = yday(smolt_quant_75_doy)
  )

# Join smolting and sea migration dates
all_dates_migration <- merge(all_dates_smolt, all_dates_sea, by = c("river", "cohort"))

# Export final migration date table
write_fst(all_dates_migration, path = "R/00_derived_data/Year_Migration_Dates_River_Sea.fst")