

# ══════════════════════════════════════════════════════════════════════════════
# SECTION 1: HEADER
# ══════════════════════════════════════════════════════════════════════════════
#
# Computes cohort-weighted temperature metrics (mean, median, variance, degree
# days, PGTI) during the growth and emergence periods for salmon cohorts of
# the Saint-Jean and Trinite rivers.
#
# Inputs:
#   - R/00_raw_data/Temperature_Discharge_River/
#       CEQEAU_Temperature_Discharge_1979_2024_SJ.csv
#       CEQEAU_Temperature_Discharge_1979_2024_TR.csv
#       Simulated daily water temperature for Saint-Jean and Trinite (CSV)
#   - R/01_derived_data/Smolt_Proportions.fst
#       Smolt age-class proportions by river and cohort year (FST)
#   - R/01_derived_data/GrowthPeriods/Growth_Periods_STJ.fst
#       Annual growth period (start/end DOY) for Saint-Jean (FST)
#   - R/01_derived_data/GrowthPeriods/Growth_Periods_TRI.fst
#       Annual growth period (start/end DOY) for Trinite (FST)
#
# Outputs:
#   - R/03_clean_data/River/River_Temperatures.fst
#       Cohort-level temperature metrics for both rivers (FST)
#
# ══════════════════════════════════════════════════════════════════════════════


# ══════════════════════════════════════════════════════════════════════════════
# SECTION 2: LIBRARIES
# ══════════════════════════════════════════════════════════════════════════════

library(fst)
library(dplyr)
library(lubridate)
library(ggplot2)
library(ggpubr)
library(tidyr)
library(modi)
library(ggridges)
library(mgcv)


# ══════════════════════════════════════════════════════════════════════════════
# SECTION 3: WORKING DIRECTORY
# ══════════════════════════════════════════════════════════════════════════════

# ── Working directory ──────────────────────────────────────────────────────
# Automatically detects the repository root based on the script location.
# No hardcoded path — works on any machine.
current_file <- rstudioapi::getActiveDocumentContext()$path
path_parts   <- unlist(strsplit(normalizePath(current_file, winslash = "/"), "/"))
target_index <- which(path_parts == "phd-chapter3-Atlantic-Salmon")
base_path    <- paste(path_parts[1:target_index], collapse = "/")
setwd(base_path)


# ══════════════════════════════════════════════════════════════════════════════
# SECTION 4: DATA IMPORT
# ══════════════════════════════════════════════════════════════════════════════

# ── Daily water temperature — Saint-Jean ──────────────────────────────────────
# SOURCE: CEQEAU hydrological model outputs
# STATUS: Confidential — not included in this repository.
#         An example file with identical structure and simulated data is
#         available at the same path with the suffix _EXAMPLE.csv.
#         To request access, contact the data provider once the thesis
#         is published.
temp_stj <- read.csv(
  file.path(base_path,
            "R/00_raw_data/Temperature_Discharge_River",
            "CEQEAU_Temperature_Discharge_1979_2024_SJ.csv"))


# ── Daily water temperature — Trinite ─────────────────────────────────────────
# SOURCE: CEQEAU hydrological model outputs
# STATUS: Confidential — not included in this repository.
#         An example file with identical structure and simulated data is
#         available at the same path with the suffix _EXAMPLE.csv.
#         To request access, contact the data provider once the thesis
#         is published.
temp_tri <- read.csv(
  file.path(base_path,
            "R/00_raw_data/Temperature_Discharge_River",
            "CEQEAU_Temperature_Discharge_1979_2024_TR.csv"))


# ── Smolt age-class proportions ───────────────────────────────────────────────
# SOURCE: Quebec salmon monitoring program (MELCCFP)
# STATUS: Confidential — not included in this repository.
#         An example file with identical structure and simulated data is
#         available at the same path with the suffix _EXAMPLE.fst.
#         To request access, contact the MELCCFP once the thesis is published.
prop_smolt <- read_fst(
  file.path(base_path, "R/01_derived_data/Smolt_Proportions.fst"))


# ── Annual growth periods ─────────────────────────────────────────────────────
# SOURCE: Derived from temperature data
# STATUS: Too large for GitHub — not included in this repository.
#         Generated by running: Growth_Periods.R
gr_period_stj <- read_fst(
  file.path(base_path,
            "R/01_derived_data/Growth_Periods_StJean.fst"))
gr_period_tri <- read_fst(
  file.path(base_path,
            "R/01_derived_data/Growth_Periods_Trinite.fst"))


# ══════════════════════════════════════════════════════════════════════════════
# SECTION 5: CONFIGURATION
# ══════════════════════════════════════════════════════════════════════════════

# Fixed DOY bounds for hatching and emergence (same across all years)
hatch_start_doy <- 98   # Start DOY of the hatching period
hatch_end_doy   <- 136  # End DOY of the hatching period
em_start_doy    <- 137  # Start DOY of the emergence period
em_end_doy      <- 154  # End DOY of the emergence period

# Month bounds for the winter temperature overview plot
beginning_period_plot <- 10  # Start month (October)
ending_period_plot    <- 7   # End month (July)

# PGTI thermal parameters (Ouellet-Proulx et al. 2023)
pgti_Tmin <- 6   # Lower temperature threshold for growth
pgti_Topt <- 18  # Optimal temperature for growth
pgti_Tmax <- 27  # Upper temperature threshold for growth
pgti_kopt <- 1   # Maximum normalized growth rate

# Degree-day thresholds (Rooke et al. 2019)
dd_cold_threshold <- 16  # Cold stress threshold (degrees C)
dd_heat_threshold <- 20  # Heat stress threshold (degrees C)


# ══════════════════════════════════════════════════════════════════════════════
# SECTION 6: FUNCTIONS
# ══════════════════════════════════════════════════════════════════════════════

# ── weighted_median ───────────────────────────────────────────────────────────
# Purpose: Computes a weighted median by ordering values and finding the point
#   where cumulative weights reach 0.5.
# Parameters:
#   x   numeric vector of values
#   w   numeric vector of weights (same length as x)
# Returns: scalar weighted median value.

weighted_median <- function(x, w) {
  
  keep <- !is.na(x) & !is.na(w)
  x    <- x[keep]
  w    <- w[keep]
  
  o <- order(x)
  x <- x[o]
  w <- w[o]
  
  cum_w <- cumsum(w) / sum(w)
  x[which(cum_w >= 0.5)[1]]
}


# ── weighted_co_temp ──────────────────────────────────────────────────────────
# Purpose: Computes cohort-weighted mean, median, and variance of daily water
#   temperature during a specified seasonal period, weighting each freshwater
#   year by the proportion of the cohort still present in the river at that age.
# Parameters:
#   smolt_data       data frame with columns cohort, smolt_prop_2yr–5yr
#   temperature_data data frame with columns year, doy, temperature_c
#   periods          data frame with columns year, start_doy, end_doy
# Returns: data frame with columns cohort, co_mean_temp, co_median_temp,
#   co_var_temp, restricted to cohorts with at least one non-NA proportion.

weighted_co_temp <- function(smolt_data, temperature_data, periods) {
  
  years                    <- unique(smolt_data$cohort)
  smolt_data$co_mean_temp   <- NA
  smolt_data$co_median_temp <- NA
  smolt_data$co_var_temp    <- NA
  
  for (i in seq_along(years)) {
    
    smolt_data_i <- smolt_data %>% dplyr::filter(cohort == years[i])
    
    # i is the egg-deposition year; growth season t+0 maps to calendar year i+1
    extract_temp <- function(offset) {
      period_i <- periods %>% filter(year == smolt_data_i$cohort + offset)
      if (nrow(period_i) == 0 ||
          is.na(period_i$start_doy) ||
          is.na(period_i$end_doy)) return(NA_real_)
      if (!years[i] + offset %in% temperature_data$year) return(NA_real_)
      vals <- temperature_data %>%
        dplyr::filter(year == years[i] + offset,
                      doy  >= period_i$start_doy,
                      doy  <= period_i$end_doy) %>%
        dplyr::pull(temperature_c)
      if (length(vals) == 0) NA_real_ else vals
    }
    
    t_0 <- extract_temp(1)
    t_1 <- extract_temp(2)
    t_2 <- extract_temp(3)
    t_3 <- extract_temp(4)
    t_4 <- extract_temp(5)
    t_5 <- extract_temp(6)
    
    p2 <- ifelse(is.na(smolt_data_i$smolt_prop_2yr), 0,
                 smolt_data_i$smolt_prop_2yr)
    p3 <- ifelse(is.na(smolt_data_i$smolt_prop_3yr), 0,
                 smolt_data_i$smolt_prop_3yr)
    p4 <- ifelse(is.na(smolt_data_i$smolt_prop_4yr), 0,
                 smolt_data_i$smolt_prop_4yr)
    p5 <- ifelse(is.na(smolt_data_i$smolt_prop_5yr), 0,
                 smolt_data_i$smolt_prop_5yr)
    
    x_all <- c(t_0, t_1, t_2, t_3, t_4, t_5)
    w_all <- c(
      rep(1,                              length(t_0)),
      rep(1,                              length(t_1)),
      rep(max(c(0, 1 - p2)),              length(t_2)),
      rep(max(c(0, 1 - p2 - p3)),         length(t_3)),
      rep(max(c(0, 1 - p2 - p3 - p4)),    length(t_4)),
      rep(max(c(0, 1 - p2 - p3 - p4 - p5)), length(t_5))
    )
    
    smolt_data$co_mean_temp[i]   <- weighted.mean(
      x = x_all, w = w_all, na.rm = FALSE)
    smolt_data$co_median_temp[i] <- weighted_median(
      x = x_all, w = w_all)
    
    if (length(x_all) > 0 && length(w_all) > 0) {
      smolt_data$co_var_temp[i] <- weighted.var(
        x = x_all, w = w_all, na.rm = FALSE)
    } else {
      smolt_data$co_var_temp[i] <- NA
    }
  }
  
  smolt_data %>%
    dplyr::filter(!(is.na(smolt_data$smolt_prop_2yr) &
                      is.na(smolt_data$smolt_prop_3yr) &
                      is.na(smolt_data$smolt_prop_4yr) &
                      is.na(smolt_data$smolt_prop_5yr))) %>%
    dplyr::select(cohort, co_mean_temp, co_median_temp, co_var_temp) %>%
    as.data.frame()
}


# ── dd_em ─────────────────────────────────────────────────────────────────────
# Purpose: Computes the sum of temperatures above or below a threshold during
#   the emergence period of the first freshwater year (not cohort-weighted).
# Parameters:
#   temperature_data  data frame with columns year, doy, temperature_c
#   threshold         numeric; temperature threshold in degrees C
#   over              logical; TRUE = sum above threshold, FALSE = sum below
#   periods           data frame with columns year, start_doy, end_doy
# Returns: data frame with columns cohort and one named degree-day column.

dd_em <- function(temperature_data, threshold, over = TRUE, periods) {
  
  years  <- unique(temperature_data$year)
  result <- data.frame(cohort = years, dd_threshold = NA)
  
  for (i in seq_along(years)) {
    
    result_i <- result %>% dplyr::filter(cohort == years[i])
    
    period_i <- periods %>% filter(year == result_i$cohort + 1)
    if (nrow(period_i) == 0 ||
        is.na(period_i$start_doy) ||
        is.na(period_i$end_doy)) {
      t_0 <- NA_real_
    } else {
      if (!years[i] + 1 %in% temperature_data$year) {
        t_0 <- NA_real_
      } else {
        t_0 <- temperature_data %>%
          dplyr::filter(year == years[i] + 1,
                        doy  >= period_i$start_doy,
                        doy  <= period_i$end_doy) %>%
          dplyr::pull(temperature_c)
        if (length(t_0) == 0) t_0 <- NA_real_
      }
    }
    
    if (nrow(period_i) == 0) next
    
    if (over) {
      result$dd_threshold[i] <- sum(t_0[which(t_0 >= threshold)])
    } else {
      result$dd_threshold[i] <- sum(t_0[which(t_0 <= threshold)])
    }
  }
  
  colname_idx <- which(colnames(result) == "dd_threshold")
  colnames(result)[colname_idx] <- if (over) {
    paste("dd", "o", threshold, sep = "_")
  } else {
    paste("dd", "u", threshold, sep = "_")
  }
  
  return(result)
}


# ── dd_cohort ─────────────────────────────────────────────────────────────────
# Purpose: Computes a cohort-weighted sum of temperatures above or below a
#   threshold during the growth period, weighting each freshwater year by the
#   proportion of the cohort still present in the river at that age.
# Parameters:
#   smolt_data        data frame with columns cohort, smolt_prop_2yr–5yr
#   temperature_data  data frame with columns year, doy, temperature_c
#   threshold         numeric; temperature threshold in degrees C
#   over              logical; TRUE = sum above threshold, FALSE = sum below
#   periods           data frame with columns year, start_doy, end_doy
# Returns: data frame with columns cohort and one named degree-day column.

dd_cohort <- function(smolt_data, temperature_data, threshold,
                      over = TRUE, periods) {
  
  years                      <- unique(smolt_data$cohort)
  smolt_data$co_dd_threshold <- NA
  
  for (i in seq_along(years)) {
    
    smolt_data_i <- smolt_data %>% dplyr::filter(cohort == years[i])
    
    extract_temp <- function(offset) {
      period_i <- periods %>% filter(year == smolt_data_i$cohort + offset)
      if (nrow(period_i) == 0 ||
          is.na(period_i$start_doy) ||
          is.na(period_i$end_doy)) return(NA_real_)
      if (!years[i] + offset %in% temperature_data$year) return(NA_real_)
      vals <- temperature_data %>%
        dplyr::filter(year == years[i] + offset,
                      doy  >= period_i$start_doy,
                      doy  <= period_i$end_doy) %>%
        dplyr::pull(temperature_c)
      if (length(vals) == 0) NA_real_ else vals
    }
    
    t_0 <- extract_temp(1)
    t_1 <- extract_temp(2)
    t_2 <- extract_temp(3)
    t_3 <- extract_temp(4)
    t_4 <- extract_temp(5)
    t_5 <- extract_temp(6)
    
    p2 <- ifelse(is.na(smolt_data_i$smolt_prop_2yr), 0,
                 smolt_data_i$smolt_prop_2yr)
    p3 <- ifelse(is.na(smolt_data_i$smolt_prop_3yr), 0,
                 smolt_data_i$smolt_prop_3yr)
    p4 <- ifelse(is.na(smolt_data_i$smolt_prop_4yr), 0,
                 smolt_data_i$smolt_prop_4yr)
    p5 <- ifelse(is.na(smolt_data_i$smolt_prop_5yr), 0,
                 smolt_data_i$smolt_prop_5yr)
    
    dd_sum <- function(t, w) w * sum(if (over) t[t >= threshold] else
      t[t <= threshold])
    
    smolt_data$co_dd_threshold[i] <- sum(c(
      dd_sum(t_0, 1),
      dd_sum(t_1, 1),
      dd_sum(t_2, max(c(0, 1 - p2))),
      dd_sum(t_3, max(c(0, 1 - p2 - p3))),
      dd_sum(t_4, max(c(0, 1 - p2 - p3 - p4))),
      dd_sum(t_5, max(c(0, 1 - p2 - p3 - p4 - p5)))
    ))
  }
  
  smolt_data <- smolt_data %>%
    dplyr::filter(!(is.na(smolt_data$smolt_prop_2yr) &
                      is.na(smolt_data$smolt_prop_3yr) &
                      is.na(smolt_data$smolt_prop_4yr) &
                      is.na(smolt_data$smolt_prop_5yr))) %>%
    dplyr::select(cohort, co_dd_threshold) %>%
    as.data.frame()
  
  colname_idx <- which(colnames(smolt_data) == "co_dd_threshold")
  colnames(smolt_data)[colname_idx] <- if (over) {
    paste("dd", "o", threshold, sep = "_")
  } else {
    paste("dd", "u", threshold, sep = "_")
  }
  
  return(smolt_data)
}


# ── pgti ──────────────────────────────────────────────────────────────────────
# Purpose: Computes the Potential Growth Thermal Index (PGTI) for a vector of
#   daily temperatures using a unimodal curve bounded by Tmin and Tmax
#   (Ouellet-Proulx et al. 2023).
# Parameters:
#   temperature_data  numeric vector of daily temperatures (degrees C)
#   Tmin              lower growth threshold (default: 6)
#   Topt              optimal growth temperature (default: 18)
#   Tmax              upper growth threshold (default: 27)
#   kopt              maximum normalized growth rate (default: 1)
# Returns: numeric vector of PGTI values (same length as temperature_data).

pgti <- function(temperature_data,
                 Tmin = 6, Topt = 18, Tmax = 27, kopt = 1) {
  
  f   <- rep(0, length(temperature_data))
  idx <- which(temperature_data > Tmin & temperature_data < Tmax)
  num <- (temperature_data[idx] - Tmin) * (temperature_data[idx] - Tmax)
  den <- num - (temperature_data[idx] - Topt)^2
  f[idx] <- kopt * (num / den)
  return(f)
}


# ── weighted_co_pgti ──────────────────────────────────────────────────────────
# Purpose: Computes the cohort-weighted annual sum of PGTI and 1-PGTI across
#   all freshwater years, using smolt age-class proportions as weights.
# Parameters:
#   smolt_data        data frame with columns cohort, smolt_prop_2yr–5yr
#   temperature_data  data frame with columns year, doy, temperature_c
# Returns: data frame with columns cohort, co_mean_pgti, co_mean_inv_pgti.

weighted_co_pgti <- function(smolt_data, temperature_data) {
  
  years                       <- unique(smolt_data$cohort)
  smolt_data$co_mean_pgti     <- NA
  smolt_data$co_mean_inv_pgti <- NA
  
  for (i in seq_along(years)) {
    
    smolt_data_i <- smolt_data %>% dplyr::filter(cohort == years[i])
    
    # Compute annual PGTI sums for each freshwater year of the cohort
    pgti_year <- function(offset) {
      temperature_data %>%
        dplyr::filter(year == years[i] + offset) %>%
        dplyr::mutate(pgti     = pgti(temperature_c),
                      inv_pgti = 1 - pgti(temperature_c)) %>%
        dplyr::group_by(year) %>%
        dplyr::summarise(em_sum_ptgi     = sum(pgti),
                         em_sum_inv_pgti = sum(inv_pgti))
    }
    
    t_0 <- pgti_year(1)
    t_1 <- pgti_year(2)
    t_2 <- pgti_year(3)
    t_3 <- pgti_year(4)
    t_4 <- pgti_year(5)
    t_5 <- pgti_year(6)
    
    p2 <- ifelse(is.na(smolt_data_i$smolt_prop_2yr), 0,
                 smolt_data_i$smolt_prop_2yr)
    p3 <- ifelse(is.na(smolt_data_i$smolt_prop_3yr), 0,
                 smolt_data_i$smolt_prop_3yr)
    p4 <- ifelse(is.na(smolt_data_i$smolt_prop_4yr), 0,
                 smolt_data_i$smolt_prop_4yr)
    p5 <- ifelse(is.na(smolt_data_i$smolt_prop_5yr), 0,
                 smolt_data_i$smolt_prop_5yr)
    
    w_vec <- c(
      rep(1,                              length(t_0$em_sum_ptgi)),
      rep(1,                              length(t_1$em_sum_ptgi)),
      rep(max(c(0, 1 - p2)),              length(t_2$em_sum_ptgi)),
      rep(max(c(0, 1 - p2 - p3)),         length(t_3$em_sum_ptgi)),
      rep(max(c(0, 1 - p2 - p3 - p4)),    length(t_4$em_sum_ptgi)),
      rep(max(c(0, 1 - p2 - p3 - p4 - p5)), length(t_5$em_sum_ptgi))
    )
    
    smolt_data$co_mean_pgti[i] <- weighted.mean(
      x = c(t_0$em_sum_ptgi, t_1$em_sum_ptgi, t_2$em_sum_ptgi,
            t_3$em_sum_ptgi, t_4$em_sum_ptgi, t_5$em_sum_ptgi),
      w = w_vec, na.rm = FALSE)
    
    smolt_data$co_mean_inv_pgti[i] <- weighted.mean(
      x = c(t_0$em_sum_inv_pgti, t_1$em_sum_inv_pgti, t_2$em_sum_inv_pgti,
            t_3$em_sum_inv_pgti, t_4$em_sum_inv_pgti, t_5$em_sum_inv_pgti),
      w = w_vec, na.rm = FALSE)
  }
  
  smolt_data %>%
    dplyr::filter(!(is.na(smolt_data$smolt_prop_2yr) &
                      is.na(smolt_data$smolt_prop_3yr) &
                      is.na(smolt_data$smolt_prop_4yr) &
                      is.na(smolt_data$smolt_prop_5yr))) %>%
    dplyr::select(cohort, co_mean_pgti, co_mean_inv_pgti) %>%
    as.data.frame()
}


# ── add_limits ────────────────────────────────────────────────────────────────
# Purpose: Produces a faceted cohort time-series plot with consistent y-axis
#   limits across rivers, and grey shading over cohort years with missing
#   smolt proportion data.
# Parameters:
#   df           long-format data frame with columns cohort, threshold, days
#   limits_y     data frame with columns threshold, ymin, ymax
#   shade_start  numeric vector of cohort years to shade (missing data)
# Returns: a ggplot object.

add_limits <- function(df, limits_y, shade_start) {
  
  p <- df %>%
    left_join(limits_y, by = "threshold") %>%
    ggplot(aes(x = cohort, y = days)) +
    geom_line(group = 1, color = "steelblue") +
    geom_point(color = "steelblue", size = 1.5) +
    geom_blank(aes(y = ymin)) +
    geom_blank(aes(y = ymax)) +
    facet_wrap(~ threshold, scales = "free_y", ncol = 1) +
    theme_bw(base_size = 12) +
    theme(
      strip.text       = element_text(face = "bold"),
      axis.text.x      = element_text(angle = 45, hjust = 1),
      plot.title       = element_text(hjust = 0.5),
      panel.grid.minor = element_blank()
    )
  
  # Add a grey band for each cohort year with missing smolt proportion data
  for (yr in shade_start) {
    p <- p + annotate("rect",
                      xmin  = yr - 0.5, xmax = yr + 0.5,
                      ymin  = -Inf,     ymax = Inf,
                      fill  = "grey60", alpha = 0.4)
  }
  
  return(p)
}


# ══════════════════════════════════════════════════════════════════════════════
# SECTION 7: MAIN SCRIPT
# ══════════════════════════════════════════════════════════════════════════════

# ── Reformat temperature data ─────────────────────────────────────────────────

colnames(temp_stj)[
  which(colnames(temp_stj) == "Observed.Discharge..m3.s.")] <-
  "Observed_Discharge_m3s"
colnames(temp_stj)[
  which(colnames(temp_stj) == "Simulated.Discharge..m3.s.")] <-
  "Simulated_Discharge_m3s"
colnames(temp_stj)[
  which(colnames(temp_stj) == "Tw..degree.C.")] <-
  "Temperature_C"

colnames(temp_tri)[
  which(colnames(temp_tri) == "Observed.Discharge..RatingCurve...m3.s.")] <-
  "Observed_Discharge_m3s"
colnames(temp_tri)[
  which(colnames(temp_tri) == "Simulated.Discharge..m3.s.")] <-
  "Simulated_Discharge_m3s"
colnames(temp_tri)[
  which(colnames(temp_tri) == "Simulated.Tw..degree.C.")] <-
  "Temperature_C"

colnames(temp_stj) <- tolower(colnames(temp_stj))
colnames(temp_tri) <- tolower(colnames(temp_tri))

# Parse date strings using locale C to ensure English month abbreviations
old_locale <- Sys.getlocale("LC_TIME")
Sys.setlocale("LC_TIME", "C")
temp_stj$date <- as.Date(temp_stj$date, format = "%d-%b-%Y")
temp_tri$date <- as.Date(temp_tri$date, format = "%d-%b-%Y")
Sys.setlocale("LC_TIME", old_locale)

temp_stj <- subset(temp_stj, select = c("date", "temperature_c"))
temp_tri <- subset(temp_tri, select = c("date", "temperature_c"))

temp_stj$year  <- year(temp_stj$date)
temp_stj$month <- month(temp_stj$date)
temp_stj$day   <- day(temp_stj$date)
temp_stj$doy   <- yday(temp_stj$date)

temp_tri$year  <- year(temp_tri$date)
temp_tri$month <- month(temp_tri$date)
temp_tri$day   <- day(temp_tri$date)
temp_tri$doy   <- yday(temp_tri$date)


# ── Build period lookup tables and split smolt proportions ────────────────────

hatch_period <- data.frame(
  year      = sort(unique(gr_period_stj$year)),
  start_doy = hatch_start_doy,
  end_doy   = hatch_end_doy
)

em_period <- data.frame(
  year      = sort(unique(gr_period_stj$year)),
  start_doy = em_start_doy,
  end_doy   = em_end_doy
)

prop_smolt_sub_sj <- prop_smolt %>% dplyr::filter(river == "stj")
prop_smolt_sub_tr <- prop_smolt %>% dplyr::filter(river == "tri")


# ── Exploratory ridge plots of temperature distributions ─────────────────────

ggplot(temp_tri %>% filter(month >= 4 & month <= 10),
       aes(x = temperature_c, y = factor(year), fill = factor(year))) +
  geom_density_ridges(stat = "binline", bins = 60, scale = 5,
                      color = "grey20", linewidth = 0.3) +
  scale_fill_viridis_d(option = "C", direction = -1) +
  scale_x_continuous(limits  = c(0, 26),
                     breaks  = seq(0, 26, by = 2),
                     expand  = c(0, 0)) +
  labs(title = "Distribution of water temperature in the Trinite River (April-October)",
       x = "Temperature (C)", y = NULL) +
  theme_ridges() +
  theme(legend.position   = "none",
        plot.title        = element_text(size = 12, face = "bold"),
        axis.title.x      = element_text(size = 10),
        axis.text.y       = element_text(size = 8))

ggplot(temp_stj %>% filter(month >= 4 & month <= 10),
       aes(x = temperature_c, y = factor(year), fill = factor(year))) +
  geom_density_ridges(stat = "binline", bins = 60, scale = 5,
                      color = "grey20", linewidth = 0.3) +
  scale_fill_viridis_d(option = "C", direction = -1) +
  scale_x_continuous(limits  = c(0, 26),
                     breaks  = seq(0, 26, by = 2),
                     expand  = c(0, 0)) +
  labs(title = "Distribution of water temperature in the St. Jean River (April-October)",
       x = "Temperature (C)", y = NULL) +
  theme_ridges() +
  theme(legend.position   = "none",
        plot.title        = element_text(size = 12, face = "bold"),
        axis.title.x      = element_text(size = 10),
        axis.text.y       = element_text(size = 8))


# ── Winter temperature check (comparison with Rooke et al. 2019) ─────────────

# Assign a fictitious year so that Oct-Jul spans a continuous x-axis
temp_winter_stj <- temp_stj %>%
  filter(month >= beginning_period_plot | month <= ending_period_plot) %>%
  mutate(
    winter_date = as.Date(ifelse(month >= beginning_period_plot,
                                 paste0("2000-", month, "-", day),
                                 paste0("2001-", month, "-", day)))
  )

temp_winter_tri <- temp_tri %>%
  filter(month >= beginning_period_plot | month <= ending_period_plot) %>%
  mutate(
    winter_date = as.Date(ifelse(month >= beginning_period_plot,
                                 paste0("2000-", month, "-", day),
                                 paste0("2001-", month, "-", day)))
  )

# Shared theme for the winter plots
theme_winter <- theme_minimal(base_size = 12) +
  theme(axis.text.x      = element_text(angle = 45, hjust = 1),
        panel.grid.minor = element_blank())

ggplot(temp_winter_stj,
       aes(x = winter_date, y = temperature_c, group = year)) +
  geom_line(alpha = 0.4, color = "grey50") +
  geom_smooth(aes(group = 1), method = "gam", formula = y ~ s(x, k = 20),
              color = "black", linewidth = 1) +
  geom_vline(xintercept = as.Date(em_period$start_doy - 1,
                                  origin = "2001-01-01"),
             color = "tomato", linetype = "dashed") +
  geom_vline(xintercept = as.Date(em_period$end_doy - 1,
                                  origin = "2001-01-01"),
             color = "tomato", linetype = "dashed") +
  scale_x_date(date_labels = "%m-%d", date_breaks = "1 month") +
  labs(x = "Date", y = "Water temperature (C)") +
  theme_winter

ggplot(temp_winter_tri,
       aes(x = winter_date, y = temperature_c, group = year)) +
  geom_line(alpha = 0.4, color = "grey50") +
  geom_smooth(aes(group = 1), method = "gam", formula = y ~ s(x, k = 20),
              color = "black", linewidth = 1) +
  geom_vline(xintercept = as.Date(em_period$start_doy - 1,
                                  origin = "2001-01-01"),
             color = "tomato", linetype = "dashed") +
  geom_vline(xintercept = as.Date(em_period$end_doy - 1,
                                  origin = "2001-01-01"),
             color = "tomato", linetype = "dashed") +
  scale_x_date(date_labels = "%m-%d", date_breaks = "1 month") +
  labs(x = "Date", y = "Water temperature (C)") +
  theme_winter

# Strictly in terms of temperatures during the emergence period, we are about
# a week or two earlier than Rooke et al. (2019). They report that temperature
# during emergence is around 10-11 C, whereas using the same emergence period:
#   7.5 to 10 C in the St. Jean River (10-11 C ~1-2 weeks later)
#   6 to 11 C in the Trinite River   (10-11 C ~0-2 weeks later)


# ── Cohort mean, median, and variance temperature during the growth season ────

# Shared theme for cohort time-series plots
theme_cohort <- theme_bw(base_size = 12) +
  theme(axis.text.x      = element_text(angle = 45, hjust = 1),
        panel.grid.minor = element_blank(),
        plot.title        = element_text(hjust = 0.5))

weighted_co_season_sj <- weighted_co_temp(
  smolt_data       = prop_smolt_sub_sj,
  temperature_data = temp_stj,
  periods          = gr_period_stj) %>%
  dplyr::rename(co_gr_mean_temp   = co_mean_temp,
                co_gr_median_temp = co_median_temp,
                co_gr_var_temp    = co_var_temp)

weighted_co_season_tr <- weighted_co_temp(
  smolt_data       = prop_smolt_sub_tr,
  temperature_data = temp_tri,
  periods          = gr_period_tri) %>%
  dplyr::rename(co_gr_mean_temp   = co_mean_temp,
                co_gr_median_temp = co_median_temp,
                co_gr_var_temp    = co_var_temp)

ggarrange(
  ggarrange(
    ggplot(weighted_co_season_sj,
           aes(x = cohort, y = co_gr_mean_temp)) +
      geom_point(size = 1.5) + geom_line() +
      labs(title = "St-Jean River") + theme_cohort,
    ggplot(weighted_co_season_tr,
           aes(x = cohort, y = co_gr_mean_temp)) +
      geom_point(size = 1.5) + geom_line() +
      labs(title = "Trinite River") + theme_cohort,
    ncol = 2),
  ggarrange(
    ggplot(weighted_co_season_sj,
           aes(x = cohort, y = co_gr_median_temp)) +
      geom_point(size = 1.5) + geom_line() +
      labs(title = "St-Jean River") + theme_cohort,
    ggplot(weighted_co_season_tr,
           aes(x = cohort, y = co_gr_median_temp)) +
      geom_point(size = 1.5) + geom_line() +
      labs(title = "Trinite River") + theme_cohort,
    ncol = 2),
  ncol = 1)

ggarrange(
  ggplot(weighted_co_season_sj,
         aes(x = cohort, y = co_gr_var_temp)) +
    geom_point(size = 1.5) + geom_line() +
    labs(title = "St-Jean River") + theme_cohort,
  ggplot(weighted_co_season_tr,
         aes(x = cohort, y = co_gr_var_temp)) +
    geom_point(size = 1.5) + geom_line() +
    labs(title = "Trinite River") + theme_cohort,
  ncol = 2)


# ── Temperature statistics during the emergence period ───────────────────────

emergence_sj <- temp_stj %>%
  dplyr::filter(doy >= unique(em_period$start_doy),
                doy <= unique(em_period$end_doy)) %>%
  dplyr::rename(cohort = year) %>%
  dplyr::group_by(cohort) %>%
  dplyr::summarise(em_mean_temp   = mean(temperature_c),
                   em_median_temp = median(temperature_c),
                   em_var_temp    = var(temperature_c))

emergence_tr <- temp_tri %>%
  dplyr::filter(doy >= unique(em_period$start_doy),
                doy <= unique(em_period$end_doy)) %>%
  dplyr::rename(cohort = year) %>%
  dplyr::group_by(cohort) %>%
  dplyr::summarise(em_mean_temp   = mean(temperature_c),
                   em_median_temp = median(temperature_c),
                   em_var_temp    = var(temperature_c))

ggarrange(
  ggarrange(
    ggplot(emergence_sj, aes(x = cohort, y = em_mean_temp)) +
      geom_point(size = 1.5) + geom_line() +
      labs(title = "St-Jean River") + theme_cohort,
    ggplot(emergence_tr, aes(x = cohort, y = em_mean_temp)) +
      geom_point(size = 1.5) + geom_line() +
      labs(title = "Trinite River") + theme_cohort,
    ncol = 2),
  ggarrange(
    ggplot(emergence_sj, aes(x = cohort, y = em_median_temp)) +
      geom_point(size = 1.5) + geom_line() +
      labs(title = "St-Jean River") + theme_cohort,
    ggplot(emergence_tr, aes(x = cohort, y = em_median_temp)) +
      geom_point(size = 1.5) + geom_line() +
      labs(title = "Trinite River") + theme_cohort,
    ncol = 2),
  ncol = 1)


# ── Degree days above/below thresholds during emergence (Rooke et al. 2019) ──

dd_em_sj_16 <- dd_em(temp_stj, threshold = dd_cold_threshold,
                     over = FALSE, periods = em_period) %>%
  rename(em_dd_u_16_temp = dd_u_16)

dd_em_tr_16 <- dd_em(temp_tri, threshold = dd_cold_threshold,
                     over = FALSE, periods = em_period) %>%
  rename(em_dd_u_16_temp = dd_u_16)

dd_em_sj_20 <- dd_em(temp_stj, threshold = dd_heat_threshold,
                     over = TRUE, periods = em_period) %>%
  rename(em_dd_o_20_temp = dd_o_20)

dd_em_tr_20 <- dd_em(temp_tri, threshold = dd_heat_threshold,
                     over = TRUE, periods = em_period) %>%
  rename(em_dd_o_20_temp = dd_o_20)

em_combined_stj <- Reduce(function(x, y) merge(x, y, by = "cohort", all = TRUE),
                          list(dd_em_sj_16, dd_em_sj_20))
em_combined_tri <- Reduce(function(x, y) merge(x, y, by = "cohort", all = TRUE),
                          list(dd_em_tr_16, dd_em_tr_20))

em_long_stj <- em_combined_stj %>%
  pivot_longer(cols = contains("dd_"), names_to = "threshold", values_to = "days")
em_long_tri <- em_combined_tri %>%
  pivot_longer(cols = contains("dd_"), names_to = "threshold", values_to = "days")

em_limits_y <- bind_rows(em_long_stj, em_long_tri) %>%
  dplyr::group_by(threshold) %>%
  dplyr::summarise(ymin = min(days, na.rm = TRUE),
                   ymax = max(days, na.rm = TRUE))

ggarrange(
  ggarrange(
    ggplot(em_combined_stj, aes(x = cohort, y = em_dd_o_20_temp)) +
      geom_line(group = 1, color = "steelblue") +
      geom_point(color = "steelblue", size = 1.5) +
      labs(title = "St. Jean R.") + theme_cohort,
    ggplot(em_combined_tri, aes(x = cohort, y = em_dd_o_20_temp)) +
      geom_line(group = 1, color = "steelblue") +
      geom_point(color = "steelblue", size = 1.5) +
      labs(title = "Trinite R.") + theme_cohort,
    nrow = 1),
  ggarrange(
    ggplot(em_combined_stj, aes(x = cohort, y = em_dd_u_16_temp)) +
      geom_line(group = 1, color = "steelblue") +
      geom_point(color = "steelblue", size = 1.5) +
      labs(title = "St. Jean R.") + theme_cohort,
    ggplot(em_combined_tri, aes(x = cohort, y = em_dd_u_16_temp)) +
      geom_line(group = 1, color = "steelblue") +
      geom_point(color = "steelblue", size = 1.5) +
      labs(title = "Trinite R.") + theme_cohort,
    nrow = 1),
  ncol = 1)


# ── Degree days above/below thresholds during growth season (cohort-weighted) ─

dd_gr_cohort_sj_16 <- dd_cohort(prop_smolt_sub_sj, temp_stj,
                                threshold = dd_cold_threshold,
                                over = FALSE, periods = gr_period_stj) %>%
  rename(co_gr_dd_u_16_temp = dd_u_16)

dd_gr_cohort_tr_16 <- dd_cohort(prop_smolt_sub_tr, temp_tri,
                                threshold = dd_cold_threshold,
                                over = FALSE, periods = gr_period_tri) %>%
  rename(co_gr_dd_u_16_temp = dd_u_16)

dd_gr_cohort_sj_20 <- dd_cohort(prop_smolt_sub_sj, temp_stj,
                                threshold = dd_heat_threshold,
                                over = TRUE, periods = gr_period_stj) %>%
  rename(co_gr_dd_o_20_temp = dd_o_20)

dd_gr_cohort_tr_20 <- dd_cohort(prop_smolt_sub_tr, temp_tri,
                                threshold = dd_heat_threshold,
                                over = TRUE, periods = gr_period_tri) %>%
  rename(co_gr_dd_o_20_temp = dd_o_20)

gr_combined_stj <- Reduce(function(x, y) merge(x, y, by = "cohort", all = TRUE),
                          list(dd_gr_cohort_sj_16, dd_gr_cohort_sj_20))
gr_combined_tri <- Reduce(function(x, y) merge(x, y, by = "cohort", all = TRUE),
                          list(dd_gr_cohort_tr_16, dd_gr_cohort_tr_20))

gr_long_stj <- gr_combined_stj %>%
  pivot_longer(cols = contains("dd_"), names_to = "threshold", values_to = "days")
gr_long_tri <- gr_combined_tri %>%
  pivot_longer(cols = contains("dd_"), names_to = "threshold", values_to = "days")

gr_limits_y <- bind_rows(gr_long_stj, gr_long_tri) %>%
  dplyr::group_by(threshold) %>%
  dplyr::summarise(ymin = min(days, na.rm = TRUE),
                   ymax = max(days, na.rm = TRUE))

# Cohort years with all-NA smolt proportions are shaded to flag missing data
shade_start_sj <- prop_smolt_sub_sj$cohort[
  which(is.na(prop_smolt_sub_sj$smolt_prop_2yr) &
          is.na(prop_smolt_sub_sj$smolt_prop_3yr) &
          is.na(prop_smolt_sub_sj$smolt_prop_4yr) &
          is.na(prop_smolt_sub_sj$smolt_prop_5yr))]

shade_start_tr <- prop_smolt_sub_tr$cohort[
  which(is.na(prop_smolt_sub_tr$smolt_prop_2yr) &
          is.na(prop_smolt_sub_tr$smolt_prop_3yr) &
          is.na(prop_smolt_sub_tr$smolt_prop_4yr) &
          is.na(prop_smolt_sub_tr$smolt_prop_5yr))]

p_sj <- add_limits(gr_long_stj, gr_limits_y, shade_start_sj) +
  labs(title = "St-Jean", x = "Cohort year", y = "Days")
p_tr <- add_limits(gr_long_tri, gr_limits_y, shade_start_tr) +
  labs(title = "Trinite", x = "Cohort year", y = "Days")
ggarrange(p_sj, p_tr, nrow = 1)


# ── PGTI curve verification ───────────────────────────────────────────────────

# Diagnostic plot of the PGTI curve over the full temperature range
sim_temps       <- data.frame(temp = seq(0, 33, by = 0.01), pgti = NA)
sim_temps$pgti  <- pgti(sim_temps$temp,
                        Tmin = pgti_Tmin, Topt = pgti_Topt,
                        Tmax = pgti_Tmax, kopt = pgti_kopt)

ggplot(sim_temps, aes(x = temp, y = pgti)) +
  geom_line(linewidth = 1) +
  labs(x = "Temperature (C)", y = "PGTI") +
  theme_bw(base_size = 12) +
  theme(panel.grid.minor = element_blank())


# ── PGTI and 1-PGTI during emergence (not cohort-weighted) ───────────────────

pgti_em_tri <- temp_tri %>%
  dplyr::filter(doy >= unique(em_period$start_doy),
                doy <= unique(em_period$end_doy)) %>%
  dplyr::mutate(pgti     = pgti(temperature_c,
                                Tmin = pgti_Tmin, Topt = pgti_Topt,
                                Tmax = pgti_Tmax),
                inv_pgti = 1 - pgti) %>%
  dplyr::group_by(year) %>%
  dplyr::summarise(em_sum_ptgi     = sum(pgti),
                   em_sum_inv_pgti = sum(inv_pgti)) %>%
  dplyr::rename(cohort = year)

pgti_em_stj <- temp_stj %>%
  dplyr::filter(doy >= unique(em_period$start_doy),
                doy <= unique(em_period$end_doy)) %>%
  dplyr::mutate(pgti     = pgti(temperature_c,
                                Tmin = pgti_Tmin, Topt = pgti_Topt,
                                Tmax = pgti_Tmax),
                inv_pgti = 1 - pgti) %>%
  dplyr::group_by(year) %>%
  dplyr::summarise(em_sum_ptgi     = sum(pgti),
                   em_sum_inv_pgti = sum(inv_pgti)) %>%
  dplyr::rename(cohort = year)


# ── PGTI and 1-PGTI cohort-weighted over the full year ───────────────────────

pgti_co_year_stj <- weighted_co_pgti(
  smolt_data       = prop_smolt_sub_sj,
  temperature_data = temp_stj) %>%
  rename(co_year_mean_sum_ptgi    = co_mean_pgti,
         co_year_mean_sum_inv_ptgi = co_mean_inv_pgti)

pgti_co_year_tri <- weighted_co_pgti(
  smolt_data       = prop_smolt_sub_tr,
  temperature_data = temp_tri) %>%
  rename(co_year_mean_sum_ptgi    = co_mean_pgti,
         co_year_mean_sum_inv_ptgi = co_mean_inv_pgti)


# ── Export ────────────────────────────────────────────────────────────────────

sj_all <- Reduce(function(x, y) merge(x, y, by = "cohort", all = TRUE),
                 list(weighted_co_season_sj, emergence_sj, gr_combined_stj,
                      em_combined_stj, pgti_em_stj, pgti_co_year_stj))

tr_all <- Reduce(function(x, y) merge(x, y, by = "cohort", all = TRUE),
                 list(weighted_co_season_tr, emergence_tr, gr_combined_tri,
                      em_combined_tri, pgti_em_tri, pgti_co_year_tri))

sj_all$river <- "stj"
tr_all$river <- "tri"

data_all <- bind_rows(sj_all, tr_all) %>%
  dplyr::select(river, cohort, everything())

write_fst(data_all,
          path = file.path(base_path,
                           "R/03_clean_data/River/River_Temperatures.fst"))

