

# ══════════════════════════════════════════════════════════════════════════════
# SECTION 1: HEADER
# ══════════════════════════════════════════════════════════════════════════════
#
# Merges daily air temperature estimates from climate stations and ERA5
# rasters, validates their consistency via correlation tests, and exports a
# combined daily mean temperature series for the Saint-Jean and Trinite rivers.
#
# Inputs:
#   - R/01_derived_data/Winter_Temperature/tr_air_temp_daily_mean_stations.fst
#   - R/01_derived_data/Winter_Temperature/sj_air_temp_daily_mean_stations.fst
#       Daily mean temperature averaged across climate stations (FST)
#   - R/01_derived_data/Winter_Temperature/tr_air_temp_daily_mean_rasters.fst
#   - R/01_derived_data/Winter_Temperature/sj_air_temp_daily_mean_rasters.fst
#       Daily mean temperature derived from ERA5 rasters (FST)
#
# Outputs:
#   - R/01_derived_data/Winter_Temperature/tr_air_temp_daily_mean_combined.fst
#   - R/01_derived_data/Winter_Temperature/sj_air_temp_daily_mean_combined.fst
#       Combined daily mean temperature for Trinite and Saint-Jean (FST)
#
# ══════════════════════════════════════════════════════════════════════════════


# ══════════════════════════════════════════════════════════════════════════════
# SECTION 2: LIBRARIES
# ══════════════════════════════════════════════════════════════════════════════

library(data.table)
library(ggplot2)
library(fst)
library(lubridate)


# ══════════════════════════════════════════════════════════════════════════════
# SECTION 3: WORKING DIRECTORY
# ══════════════════════════════════════════════════════════════════════════════

# ── Working directory ──────────────────────────────────────────────────────
# Automatically detects the repository root based on the script location.
# No hardcoded path — works on any machine.
current_file <- rstudioapi::getActiveDocumentContext()$path
path_parts   <- unlist(strsplit(normalizePath(current_file, winslash = "/"), "/"))
target_index <- which(path_parts == "phd-chapter3-Atlantic-Salmon")
base_path    <- paste(path_parts[1:target_index], collapse = "/")
setwd(base_path)


# ══════════════════════════════════════════════════════════════════════════════
# SECTION 4: DATA IMPORT
# ══════════════════════════════════════════════════════════════════════════════

in_path <- file.path(base_path, "R/01_derived_data/Winter_Temperature")

# ── Station-based daily means ─────────────────────────────────────────────────
# SOURCE: Canadian climate stations via ClimateData.ca
# STATUS: Too large for GitHub — not included in this repository.
#         Generated by running: Air_Temperature_Stations.R
tr_temp_summary_station <- read_fst(
  file.path(in_path, "tr_air_temp_daily_mean_stations.fst"))
sj_temp_summary_station <- read_fst(
  file.path(in_path, "sj_air_temp_daily_mean_stations.fst"))

colnames(tr_temp_summary_station)[1] <- "date"
colnames(sj_temp_summary_station)[1] <- "date"


# ── Raster-based daily means ──────────────────────────────────────────────────
# SOURCE: ERA5 reanalysis via Copernicus Climate Data Store
# STATUS: Too large for GitHub — not included in this repository.
#         Generated by running: Air_Temperature_Raster.R
tr_temp_summary_raster <- read_fst(
  file.path(in_path, "tr_air_temp_daily_mean_rasters.fst"))
sj_temp_summary_raster <- read_fst(
  file.path(in_path, "sj_air_temp_daily_mean_rasters.fst"))


# ══════════════════════════════════════════════════════════════════════════════
# SECTION 5: CONFIGURATION
# ══════════════════════════════════════════════════════════════════════════════

# Months retained for the winter temperature analysis
months_to_keep <- c(1, 2, 3, 4, 10, 11, 12)

# Output directory for combined temperature files
out_path <- file.path(base_path, "R/01_derived_data/Winter_Temperature")


# ══════════════════════════════════════════════════════════════════════════════
# SECTION 6: FUNCTIONS
# ══════════════════════════════════════════════════════════════════════════════

# ── fill_missing_dates ────────────────────────────────────────────────────────
# Purpose: Ensures that all calendar dates within a set of target months are
#   present in a data frame, inserting rows with NA for any missing dates.
# Parameters:
#   df              data frame containing at least one date column
#   date_col        character; name of the date column (default: "date")
#   months_to_keep  integer vector of month numbers to retain and complete
# Returns: data frame with all dates for the target months present, missing
#   rows filled with NA.

fill_missing_dates <- function(df, date_col = "date",
                               months_to_keep = c(1, 2, 3, 4, 10, 11, 12)) {
  
  df[[date_col]] <- as.Date(df[[date_col]])
  df$Year  <- year(df[[date_col]])
  df$Month <- month(df[[date_col]])
  
  # Restrict to target months before building the complete date sequence
  df <- df[which(df$Month %in% months_to_keep), ]
  
  first_year  <- min(df$Year)
  last_year   <- max(df$Year)
  first_month <- min(months_to_keep)
  last_month  <- max(months_to_keep)
  
  # Build a full daily sequence covering all target months across all years
  all_dates <- data.frame(
    date = seq(
      from = as.Date(paste0(first_year,  "-", first_month, "-01")),
      to   = as.Date(paste0(last_year,   "-", last_month,  "-",
                            days_in_month(
                              as.Date(paste0(last_year, "-", last_month,
                                             "-01"))))),
      by = "day"
    ),
    TEMPORARY = NA
  )
  
  # Keep only the dates falling in the target months
  all_dates <- all_dates[which(month(all_dates$date) %in% months_to_keep), ]
  
  # Left-join to insert NA rows for any missing dates
  df_filled <- merge(all_dates, df, by = "date", all.x = TRUE)
  df_filled <- df_filled[, !names(df_filled) %in% c("TEMPORARY", "Year",
                                                    "Month")]
  return(df_filled)
}


# ══════════════════════════════════════════════════════════════════════════════
# SECTION 7: MAIN SCRIPT
# ══════════════════════════════════════════════════════════════════════════════

# ── Merge station and raster data ─────────────────────────────────────────────

tri_all <- merge(tr_temp_summary_station, tr_temp_summary_raster,
                 by = "date", all = TRUE)
stj_all <- merge(sj_temp_summary_station, sj_temp_summary_raster,
                 by = "date", all = TRUE)


# ── Validate consistency between data sources ─────────────────────────────────

# Stations and ERA5 rasters use different measurement conventions and spatial
# representations, so a systematic offset is expected and quantified here.

# Trinite: absolute difference and Wilcoxon signed-rank test
tri_diff <- abs(tri_all$Station_Mean_T - tri_all$Raster_Mean_T)
mean(tri_diff, na.rm = TRUE)
hist(tri_diff)
wilcox.test(tri_diff, mu = 0)

# Correlation between station and raster — Trinite
tri_cor_res  <- cor.test(tri_all$Station_Mean_T, tri_all$Raster_Mean_T)
tri_r_val    <- round(tri_cor_res$estimate, 3)
tri_p_val    <- signif(tri_cor_res$p.value, 3)
tri_n_val    <- tri_cor_res$parameter + 2
tri_label_txt <- paste0(" r = ", tri_r_val,
                        ",\n p = ", tri_p_val,
                        ",\n n = ", tri_n_val)

ggplot(data = tri_all, aes(x = Station_Mean_T, y = Raster_Mean_T)) +
  geom_point(alpha = 0.4, color = "grey40") +
  geom_smooth(method = "lm", se = TRUE, color = "red", linewidth = 1.2) +
  annotate("text",
           x     = min(tri_all$Station_Mean_T, na.rm = TRUE),
           y     = max(tri_all$Raster_Mean_T,  na.rm = TRUE),
           label = tri_label_txt,
           hjust = 0, vjust = 1, size = 5) +
  theme_bw()

# Saint-Jean: absolute difference and Wilcoxon signed-rank test
stj_diff <- abs(stj_all$Station_Mean_T - stj_all$Raster_Mean_T)
mean(stj_diff, na.rm = TRUE)
hist(stj_diff)
wilcox.test(stj_diff, mu = 0)

# Correlation between station and raster — Saint-Jean
stj_cor_res   <- cor.test(stj_all$Station_Mean_T, stj_all$Raster_Mean_T)
stj_r_val     <- round(stj_cor_res$estimate, 3)
stj_p_val     <- signif(stj_cor_res$p.value, 3)
stj_n_val     <- stj_cor_res$parameter + 2
stj_label_txt <- paste0(" r = ", stj_r_val,
                        ",\n p = ", stj_p_val,
                        ",\n n = ", stj_n_val)

ggplot(data = stj_all, aes(x = Station_Mean_T, y = Raster_Mean_T)) +
  geom_point(alpha = 0.4, color = "grey40") +
  geom_smooth(method = "lm", se = TRUE, color = "red", linewidth = 1.2) +
  annotate("text",
           x     = min(stj_all$Station_Mean_T, na.rm = TRUE),
           y     = max(stj_all$Raster_Mean_T,  na.rm = TRUE),
           label = stj_label_txt,
           hjust = 0, vjust = 1, size = 5) +
  theme_bw()

# Observations:
# - There is a systematic difference of ~2 C on average between the two
#   sources. Stations tend to report slightly higher temperatures than ERA5.
# - Trinite: station is on average 1.8339 C higher than raster.
# - Saint-Jean: station is on average 1.7350 C higher than raster.
# - The difference is statistically significant but small in magnitude.
#
# Rationale for combining both sources:
# - Taking the daily mean of the two sources (when both are available) smooths
#   the systematic offset and reduces deviation from the true temperature.
# - On days with only one source, that value is used directly.
# - This approach maximises daily coverage while keeping data consistent.


# ── Fill missing dates ────────────────────────────────────────────────────────

# Ensure all dates within the target months are represented before combining
tri_all <- fill_missing_dates(tri_all, months_to_keep = months_to_keep)
stj_all <- fill_missing_dates(stj_all, months_to_keep = months_to_keep)


# ── Combine station and raster temperature estimates ──────────────────────────

# Average the two sources row-wise; na.rm = TRUE allows use of a single source
# on days where only one is available
tri_all$Mean_T <- apply(
  tri_all[, c("Station_Mean_T", "Raster_Mean_T")],
  MARGIN = 1, FUN = function(x) mean(x, na.rm = TRUE))
tri_combined <- subset(tri_all, select = c("date", "Mean_T"))

stj_all$Mean_T <- apply(
  stj_all[, c("Station_Mean_T", "Raster_Mean_T")],
  MARGIN = 1, FUN = function(x) mean(x, na.rm = TRUE))
stj_combined <- subset(stj_all, select = c("date", "Mean_T"))

# Inspect remaining NA rows; expected only for Oct-Dec 2025 which fall outside
# the analysis period
sum(is.na(tri_combined$Mean_T))
tri_combined[which(is.na(tri_combined$Mean_T)), ]

sum(is.na(stj_combined$Mean_T))
stj_combined[which(is.na(stj_combined$Mean_T)), ]

# Remove rows where no temperature estimate is available from either source
tri_combined <- tri_combined[-which(is.na(tri_combined$Mean_T)), ]
stj_combined <- stj_combined[-which(is.na(stj_combined$Mean_T)), ]


# ── Export ────────────────────────────────────────────────────────────────────

write_fst(tri_combined,
          file.path(out_path, "tr_air_temp_daily_mean_combined.fst"))

write_fst(stj_combined,
          file.path(out_path, "sj_air_temp_daily_mean_combined.fst"))

