

# ══════════════════════════════════════════════════════════════════════════════
# SECTION 1: HEADER
# ══════════════════════════════════════════════════════════════════════════════
#
# Computes cohort-weighted cumulative freezing degree day (FDD) indices over
# multiple winter periods (monthly, bimonthly, and Oct-to-month) for Atlantic
# salmon cohorts of the Saint-Jean and Trinite rivers, based on the approach
# of Bisaillon (2005).
#
# Inputs:
#   - R/01_derived_data/Winter_Temperature/sj_air_temp_daily_mean_combined.fst
#   - R/01_derived_data/Winter_Temperature/tr_air_temp_daily_mean_combined.fst
#       Combined daily mean air temperature for both rivers (FST)
#   - R/01_derived_data/Smolt_Proportions.fst
#       Smolt age-class proportions by river and cohort year (FST)
#
# Outputs:
#   - R/03_clean_data/River/River_Winter_Temperatures.fst
#       Cohort-weighted FDD indices for both rivers (FST)
#
# ══════════════════════════════════════════════════════════════════════════════


# ══════════════════════════════════════════════════════════════════════════════
# SECTION 2: LIBRARIES
# ══════════════════════════════════════════════════════════════════════════════

library(fst)
library(ggplot2)
library(tidyr)
library(dplyr)
library(data.table)
library(lubridate)
library(ggpubr)
library(purrr)


# ══════════════════════════════════════════════════════════════════════════════
# SECTION 3: WORKING DIRECTORY
# ══════════════════════════════════════════════════════════════════════════════

# ── Working directory ──────────────────────────────────────────────────────
# Automatically detects the repository root based on the script location.
# No hardcoded path — works on any machine.
current_file <- rstudioapi::getActiveDocumentContext()$path
path_parts   <- unlist(strsplit(normalizePath(current_file, winslash = "/"), "/"))
target_index <- which(path_parts == "phd-chapter3-Atlantic-Salmon")
base_path    <- paste(path_parts[1:target_index], collapse = "/")
setwd(base_path)


# ══════════════════════════════════════════════════════════════════════════════
# SECTION 4: DATA IMPORT
# ══════════════════════════════════════════════════════════════════════════════

# ── Combined daily air temperature — Saint-Jean ───────────────────────────────
# SOURCE: Merged station and ERA5 raster estimates
# STATUS: Too large for GitHub — not included in this repository.
#         Generated by running: Air_Temperature_Combined.R
stj_combined <- read_fst(
  file.path(base_path,
            "R/01_derived_data/Winter_Temperature",
            "sj_air_temp_daily_mean_combined.fst"))


# ── Combined daily air temperature — Trinite ──────────────────────────────────
# SOURCE: Merged station and ERA5 raster estimates
# STATUS: Too large for GitHub — not included in this repository.
#         Generated by running: Air_Temperature_Combined.R
tri_combined <- read_fst(
  file.path(base_path,
            "R/01_derived_data/Winter_Temperature",
            "tr_air_temp_daily_mean_combined.fst"))


# ── Smolt age-class proportions ───────────────────────────────────────────────
# SOURCE: Quebec salmon monitoring program (MELCCFP)
# STATUS: Confidential — not included in this repository.
#         An example file with identical structure and simulated data is
#         available at the same path with the suffix _EXAMPLE.fst.
#         To request access, contact the MELCCFP once the thesis is published.
prop_smolt <- read_fst(
  file.path(base_path, "R/01_derived_data/Smolt_Proportions.fst"))


# ══════════════════════════════════════════════════════════════════════════════
# SECTION 6: FUNCTIONS
# ══════════════════════════════════════════════════════════════════════════════

# ── calc_dd ───────────────────────────────────────────────────────────────────
# Purpose: Computes cohort-weighted cumulative freezing degree day (FDD)
#   indices for multiple winter period definitions, weighting each freshwater
#   year by the proportion of the cohort still present at that age. Based on
#   Bisaillon (2005): FDD accumulation is negatively related to egg-fry
#   mortality.
# Parameters:
#   smolt_data        data frame with columns cohort, smolt_prop_2yr–5yr
#   temperature_data  data frame with columns date and a temperature column
#   temp_col          character; name of the temperature column to use
# Returns: data frame with columns cohort and all co_fdd_* metric columns,
#   restricted to cohorts with at least one non-NA age-class proportion.

calc_dd <- function(smolt_data, temperature_data, temp_col) {
  
  years <- unique(smolt_data$cohort)
  
  # Initialise output columns for Oct-to-month cumulative periods
  smolt_data$co_fdd_per_oc_no <- NA
  smolt_data$co_fdd_per_oc_de <- NA
  smolt_data$co_fdd_per_oc_ja <- NA
  smolt_data$co_fdd_per_oc_fe <- NA
  smolt_data$co_fdd_per_oc_ma <- NA
  smolt_data$co_fdd_per_oc_ap <- NA
  
  # Initialise output columns for monthly periods
  smolt_data$co_fdd_mon_oc <- NA
  smolt_data$co_fdd_mon_no <- NA
  smolt_data$co_fdd_mon_de <- NA
  smolt_data$co_fdd_mon_ja <- NA
  smolt_data$co_fdd_mon_fe <- NA
  smolt_data$co_fdd_mon_ma <- NA
  smolt_data$co_fdd_mon_ap <- NA
  
  # Initialise output columns for bimonthly periods
  smolt_data$co_fdd_bimon_no_de <- NA
  smolt_data$co_fdd_bimon_ja_fe <- NA
  smolt_data$co_fdd_bimon_ma_ap <- NA
  
  # Initialise output columns for days below -10 C (frazil/anchor ice proxy)
  smolt_data$co_d_minus_10_no <- NA
  smolt_data$co_d_minus_10_de <- NA
  
  # Add temporal columns to temperature data for period filtering
  temperature_data$year  <- year(temperature_data$date)
  temperature_data$month <- month(temperature_data$date)
  temperature_data$day   <- day(temperature_data$date)
  temperature_data$doy   <- yday(temperature_data$date)
  
  for (i in seq_along(years)) {
    
    # Extract smolt proportions; NA replaced by 0 only for minority age classes
    # (2yr and 5yr). Cohorts with NA at 3yr or 4yr are removed at the end.
    smolt_data_i <- smolt_data %>% filter(cohort == years[i])
    p2 <- ifelse(is.na(smolt_data_i$smolt_prop_2yr), 0,
                 smolt_data_i$smolt_prop_2yr)
    p3 <- ifelse(is.na(smolt_data_i$smolt_prop_3yr), 0,
                 smolt_data_i$smolt_prop_3yr)
    p4 <- ifelse(is.na(smolt_data_i$smolt_prop_4yr), 0,
                 smolt_data_i$smolt_prop_4yr)
    p5 <- ifelse(is.na(smolt_data_i$smolt_prop_5yr), 0,
                 smolt_data_i$smolt_prop_5yr)
    
    # Retain only negative daily temperatures; positive days contribute zero FDD
    temperature_data$dd <- ifelse(temperature_data[, temp_col] < 0,
                                  temperature_data[, temp_col], 0)
    
    # Period definitions -------------------------------------------------------
    
    # Cumulative from October 1 to end of specified month
    periods <- c(
      "oc_no" = "11", "oc_de" = "12", "oc_ja" = "01",
      "oc_fe" = "02", "oc_ma" = "03", "oc_ap" = "04"
    )
    
    # Single-month periods
    monthly_periods <- c(
      "oc" = "10", "no" = "11", "de" = "12",
      "ja" = "01", "fe" = "02", "ma" = "03", "ap" = "04"
    )
    
    # Two-consecutive-month periods
    bi_monthly_periods <- list(
      "no_de" = c("11", "12"),
      "ja_fe" = c("01", "02"),
      "ma_ap" = c("03", "04")
    )
    
    # Months used for frazil/anchor ice proxy (below -10 C)
    minus10_periods <- c("no" = "11", "de" = "12")
    
    # Extraction helpers -------------------------------------------------------
    
    extract_temp_period <- function(start_year, end_month, data) {
      start_date <- as.Date(paste0(start_year, "-10-01"))
      end_year   <- ifelse(as.numeric(end_month) < 10,
                           start_year + 1, start_year)
      end_date   <- as.Date(paste0(
        end_year, "-", end_month, "-",
        days_in_month(as.Date(paste0(end_year, "-", end_month, "-01")))))
      data %>%
        dplyr::filter(date >= start_date & date <= end_date) %>%
        dplyr::pull(dd)
    }
    
    extract_month <- function(start_year, month, data) {
      end_year <- ifelse(as.numeric(month) < 10, start_year + 1, start_year)
      data %>%
        dplyr::filter(year  == end_year &
                        month == as.numeric(month)) %>%
        dplyr::pull(dd)
    }
    
    extract_two_months <- function(start_year, months, data) {
      end_years <- ifelse(as.numeric(months) < 10, start_year + 1, start_year)
      data %>%
        dplyr::filter(
          (year == end_years[1] & month == as.numeric(months[1])) |
            (year == end_years[2] & month == as.numeric(months[2]))) %>%
        dplyr::pull(dd)
    }
    
    # Extract temperature vectors for each freshwater year of the cohort -------
    
    t_0 <- map(periods, ~ extract_temp_period(years[i] + 1, .x, temperature_data))
    t_1 <- map(periods, ~ extract_temp_period(years[i] + 2, .x, temperature_data))
    t_2 <- map(periods, ~ extract_temp_period(years[i] + 3, .x, temperature_data))
    t_3 <- map(periods, ~ extract_temp_period(years[i] + 4, .x, temperature_data))
    t_4 <- map(periods, ~ extract_temp_period(years[i] + 5, .x, temperature_data))
    t_5 <- map(periods, ~ extract_temp_period(years[i] + 6, .x, temperature_data))
    
    m_0 <- map(monthly_periods, ~ extract_month(years[i] + 1, .x, temperature_data))
    m_1 <- map(monthly_periods, ~ extract_month(years[i] + 2, .x, temperature_data))
    m_2 <- map(monthly_periods, ~ extract_month(years[i] + 3, .x, temperature_data))
    m_3 <- map(monthly_periods, ~ extract_month(years[i] + 4, .x, temperature_data))
    m_4 <- map(monthly_periods, ~ extract_month(years[i] + 5, .x, temperature_data))
    m_5 <- map(monthly_periods, ~ extract_month(years[i] + 6, .x, temperature_data))
    
    c_0 <- map(bi_monthly_periods, ~ extract_two_months(years[i] + 1, .x, temperature_data))
    c_1 <- map(bi_monthly_periods, ~ extract_two_months(years[i] + 2, .x, temperature_data))
    c_2 <- map(bi_monthly_periods, ~ extract_two_months(years[i] + 3, .x, temperature_data))
    c_3 <- map(bi_monthly_periods, ~ extract_two_months(years[i] + 4, .x, temperature_data))
    c_4 <- map(bi_monthly_periods, ~ extract_two_months(years[i] + 5, .x, temperature_data))
    c_5 <- map(bi_monthly_periods, ~ extract_two_months(years[i] + 6, .x, temperature_data))
    
    minus_0 <- map(minus10_periods, ~ extract_month(years[i] + 1, .x, temperature_data))
    minus_1 <- map(minus10_periods, ~ extract_month(years[i] + 2, .x, temperature_data))
    minus_2 <- map(minus10_periods, ~ extract_month(years[i] + 3, .x, temperature_data))
    minus_3 <- map(minus10_periods, ~ extract_month(years[i] + 4, .x, temperature_data))
    minus_4 <- map(minus10_periods, ~ extract_month(years[i] + 5, .x, temperature_data))
    minus_5 <- map(minus10_periods, ~ extract_month(years[i] + 6, .x, temperature_data))
    
    # Cohort-weighted FDD calculation ------------------------------------------
    # Weights decrease as cumulative smoltification removes individuals from
    # the freshwater population. threshold = 0 for standard FDD;
    # threshold = 10 for the -10 C proxy (absolute values below -10 C).
    calc_FDD <- function(x0, x1, x2, x3, x4, x5, threshold = 0) {
      sum(c(
        1                          * abs(x0[x0 < threshold]),
        1                          * abs(x1[x1 < threshold]),
        max(0, (1 - p2))           * abs(x2[x2 < threshold]),
        max(0, (1 - p2 - p3))      * abs(x3[x3 < threshold]),
        max(0, (1 - p2 - p3 - p4)) * abs(x4[x4 < threshold]),
        max(0, (1 - p2 - p3 - p4 - p5)) * abs(x5[x5 < threshold])
      ))
    }
    
    for (nm in names(periods)) {
      smolt_data[i, paste0("co_fdd_per_", nm)] <- calc_FDD(
        t_0[[nm]], t_1[[nm]], t_2[[nm]],
        t_3[[nm]], t_4[[nm]], t_5[[nm]], threshold = 0)
    }
    
    for (nm in names(monthly_periods)) {
      smolt_data[i, paste0("co_fdd_mon_", nm)] <- calc_FDD(
        m_0[[nm]], m_1[[nm]], m_2[[nm]],
        m_3[[nm]], m_4[[nm]], m_5[[nm]], threshold = 0)
    }
    
    for (nm in names(bi_monthly_periods)) {
      smolt_data[i, paste0("co_fdd_bimon_", nm)] <- calc_FDD(
        c_0[[nm]], c_1[[nm]], c_2[[nm]],
        c_3[[nm]], c_4[[nm]], c_5[[nm]], threshold = 0)
    }
    
    for (nm in names(minus10_periods)) {
      smolt_data[i, paste0("co_d_minus_10_", nm)] <- calc_FDD(
        minus_0[[nm]], minus_1[[nm]], minus_2[[nm]],
        minus_3[[nm]], minus_4[[nm]], minus_5[[nm]], threshold = 10)
    }
  }
  
  # Remove cohorts where all age-class proportions are NA (replacing all NAs
  # with 0 at 3yr and 4yr would introduce substantial bias in the FDD index)
  smolt_data %>%
    dplyr::filter(!(is.na(smolt_prop_2yr) &
                      is.na(smolt_prop_3yr) &
                      is.na(smolt_prop_4yr) &
                      is.na(smolt_prop_5yr))) %>%
    dplyr::select(cohort, starts_with("co_fdd")) %>%
    as.data.frame()
}


# ══════════════════════════════════════════════════════════════════════════════
# SECTION 7: MAIN SCRIPT
# ══════════════════════════════════════════════════════════════════════════════

# ── Split smolt proportions by river ─────────────────────────────────────────

prop_smolt_sub_stj <- prop_smolt %>% dplyr::filter(river == "stj")
prop_smolt_sub_tri <- prop_smolt %>% dplyr::filter(river == "tri")


# ── Compute cohort-weighted FDD indices ───────────────────────────────────────

tri_dd <- calc_dd(smolt_data       = prop_smolt_sub_tri,
                  temperature_data = tri_combined,
                  temp_col         = "Mean_T")

stj_dd <- calc_dd(smolt_data       = prop_smolt_sub_stj,
                  temperature_data = stj_combined,
                  temp_col         = "Mean_T")


# ── Diagnostic plots ──────────────────────────────────────────────────────────

tri_dd_long <- tri_dd %>%
  pivot_longer(cols = -cohort, names_to = "Month", values_to = "FDD")

tri_p <- ggplot(tri_dd_long, aes(x = cohort, y = FDD, color = Month)) +
  geom_line(linewidth = 1) +
  labs(y = "FDD", x = "Cohort", title = "Trinite") +
  theme_minimal() +
  theme(legend.title = element_blank(),
        text         = element_text(size = 12))

tri_p

stj_dd_long <- stj_dd %>%
  pivot_longer(cols = -cohort, names_to = "Month", values_to = "FDD")

stj_p <- ggplot(stj_dd_long, aes(x = cohort, y = FDD, color = Month)) +
  geom_line(linewidth = 1) +
  labs(y = "FDD", x = "Cohort", title = "St-Jean") +
  theme_minimal() +
  theme(legend.title = element_blank(),
        text         = element_text(size = 12))

stj_p

ggarrange(tri_p, stj_p, ncol = 2, common.legend = TRUE)


# ── Export ────────────────────────────────────────────────────────────────────

tri_dd$river <- "tri"
stj_dd$river <- "stj"

data_all <- bind_rows(tri_dd, stj_dd) %>%
  dplyr::select(river, cohort, everything())

write_fst(data_all, path = file.path(base_path, "R/03_clean_data/River/River_Winter_Temperatures.fst"))

