

# ══════════════════════════════════════════════════════════════════════════════
# SECTION 1: HEADER
# ══════════════════════════════════════════════════════════════════════════════
#
# Extracts and clips forest disturbance records (perturbations and partial
# perturbations) from the Quebec ecoforestry map to the Trinite watershed.
#
# Data source — ecoforestry map zone index (used to identify required tiles):
#   https://www.donneesquebec.ca/recherche/dataset/carte-ecoforestiere-avec-
#   perturbations/resource/937c8e2e-0d11-4552-b305-f32200f63790
#
# Data source — zone 22G tile (gpkg.zip, covers the Trinite watershed):
#   https://diffusion.mffp.gouv.qc.ca/Diffusion/DonneeGratuite/Foret/
#   DONNEES_FOR_ECO_SUD/Cartes_ecoforestieres_perturbations/02-Donnees/
#   Decoupage250K/
#
# Inputs:
#   - R/00_raw_data/Forest/CARTE_ECO_MAJ_22G_GPKG/CARTE_ECO_MAJ_22G.gpkg
#       Quebec ecoforestry map, zone 22G (GeoPackage)
#   - R/01_derived_data/ForestActivities/poly_watershed_TRI.shp
#       Trinite watershed polygon (shapefile)
#   - R/00_raw_data/Forest/URL_250K_MAJ.geojson
#       Index of Quebec ecoforestry map tiles at 1:250 000 scale (GeoJSON)
#
# Outputs:
#   - R/01_derived_data/ForestActivities/ForestActivity_TRI.fst
#       Forest disturbance records clipped to the Trinite watershed,
#       with area (m2), disturbance type, and year (FST format)
#
# ══════════════════════════════════════════════════════════════════════════════


# ══════════════════════════════════════════════════════════════════════════════
# SECTION 2: LIBRARIES
# ══════════════════════════════════════════════════════════════════════════════

library(stringr)
library(sf)
library(dplyr)
library(ggplot2)
library(fst)


# ══════════════════════════════════════════════════════════════════════════════
# SECTION 3: WORKING DIRECTORY
# ══════════════════════════════════════════════════════════════════════════════

# ── Working directory ──────────────────────────────────────────────────────
# Automatically detects the repository root based on the script location.
# No hardcoded path — works on any machine.
current_file <- rstudioapi::getActiveDocumentContext()$path
path_parts   <- unlist(strsplit(normalizePath(current_file, winslash = "/"), "/"))
target_index <- which(path_parts == "phd-chapter3-Atlantic-Salmon")
base_path    <- paste(path_parts[1:target_index], collapse = "/")
setwd(base_path)


# ══════════════════════════════════════════════════════════════════════════════
# SECTION 4: DATA IMPORT
# ══════════════════════════════════════════════════════════════════════════════

# ── Ecoforestry map — zone 22G ─────────────────────────────────────────────
# SOURCE: Quebec Ministry of Forests (MFFP), ecoforestry map with disturbances
# STATUS: Too large for GitHub — not included in this repository.
#         Download the gpkg.zip for zone 22G from:
#         https://diffusion.mffp.gouv.qc.ca/Diffusion/DonneeGratuite/Foret/
#         DONNEES_FOR_ECO_SUD/Cartes_ecoforestieres_perturbations/02-Donnees/
#         Decoupage250K/
gpkg_path      <- file.path(base_path,
                            "R/00_raw_data/Forest",
                            "CARTE_ECO_MAJ_22G_GPKG/CARTE_ECO_MAJ_22G.gpkg")
st_layers(gpkg_path)
pertu_original <- st_read(gpkg_path, layer = "pee_maj_22g")
pertu          <- pertu_original


# ── Trinite watershed polygon ─────────────────────────────────────────────────
# SOURCE: Generated from DEM and OSM river line
# STATUS: Too large for GitHub — not included in this repository.
#         Generated by running: watershed_delineation_TRI.R
ref_watershed <- st_read(
  file.path(base_path,
            "R/01_derived_data/ForestActivities/poly_watershed_TRI.shp")) %>%
  st_transform(st_crs(pertu))


# ── Ecoforestry tile index (1:250 000) ────────────────────────────────────────
# SOURCE: Quebec open data portal
# STATUS: Included in this repository
# Used to verify which tile(s) cover the watershed of interest
url_250k <- st_read(
  file.path(base_path, "R/00_raw_data/Forest/URL_250K_MAJ.geojson"))

ggplot() +
  geom_sf(data = ref_watershed, fill = "red", color = NA,
          alpha = 0.8, linewidth = 0.4) +
  geom_sf(data = url_250k, fill = NA, color = "grey40", linewidth = 0.4) +
  geom_sf_text(data = url_250k, aes(label = Feuillet250K), size = 3) +
  theme_minimal()


# ══════════════════════════════════════════════════════════════════════════════
# SECTION 7: MAIN SCRIPT
# ══════════════════════════════════════════════════════════════════════════════

# ── Separate and combine perturbation types ───────────────────────────────────

# Disturbance codes excluded from the analysis:
#   P   = Plantation
#   PRR = Plantation-equivalent regeneration fill
#   REA = Regeneration of a slash area
#   RIA = Regeneration of an abandoned infrastructure site
#   RPS = Recovery under a special management plan

# Stand-replacing disturbances (origine field), excluding the codes above
pertu_origine <- pertu %>%
  dplyr::filter(!origine %in% c("P", "PRR", "REA", "RIA", "RPS")) %>%
  dplyr::select(origine, an_origine) %>%
  dplyr::rename(ORIG = origine, EXERCICE = an_origine) %>%
  dplyr::mutate(Perturb = "Perturbation") %>%
  dplyr::filter(!is.na(ORIG),
                !is.na(EXERCICE),
                EXERCICE >= 1980)

# Partial disturbances (perturb field), same exclusion criteria
pertu_perturb <- pertu %>%
  dplyr::filter(!origine %in% c("P", "PRR", "REA", "RIA", "RPS")) %>%
  dplyr::select(perturb, an_perturb) %>%
  dplyr::rename(ORIG = perturb, EXERCICE = an_perturb) %>%
  dplyr::mutate(Perturb = "Partial") %>%
  dplyr::filter(!is.na(ORIG),
                !is.na(EXERCICE),
                EXERCICE >= 1980)

# Combine both disturbance types into a single layer
pertu <- rbind(pertu_origine, pertu_perturb)


# ── Clip disturbances to the Trinite watershed ────────────────────────────────

# Rough crop to the bounding box first to reduce object size before precise clip
pertu_crop    <- st_crop(pertu, st_bbox(ref_watershed))

# Precise clip on the exact watershed geometry
pertu_clipped <- st_intersection(pertu_crop, ref_watershed)

# Compute polygon area in m2
pertu_clipped$area <- as.numeric(st_area(pertu_clipped))

ggplot() +
  geom_sf(data = ref_watershed, fill = NA, color = "black", size = 0.5) +
  geom_sf(data = pertu_clipped, aes(fill = factor(EXERCICE)),
          color = NA, alpha = 0.6) +
  theme_minimal() +
  labs(fill = "Year")


# ── Export ────────────────────────────────────────────────────────────────────

pertu_df <- as.data.frame(pertu_clipped) %>%
  dplyr::select(ORIG, EXERCICE, Perturb, area)

write_fst(pertu_df,
          path = file.path(base_path,
                           "R/01_derived_data/ForestActivities",
                           "ForestActivity_TRI.fst"))

