

# ══════════════════════════════════════════════════════════════════════════════
# SECTION 1: HEADER
# ══════════════════════════════════════════════════════════════════════════════
#
# Computes a cohort-weighted mean of annual forest disturbance area for each
# salmon cohort, using smolt age-class proportions as weights, for both the
# Saint-Jean and Trinite rivers.
#
# Inputs:
#   - R/01_derived_data/ForestActivities/ForestActivity_STJ.fst
#       Forest disturbance records for the Saint-Jean watershed (FST)
#   - R/01_derived_data/ForestActivities/ForestActivity_TRI.fst
#       Forest disturbance records for the Trinite watershed (FST)
#   - R/01_derived_data/Smolt_Proportions.fst
#       Smolt age-class proportions by river and cohort year (FST)
#
# Outputs:
#   - R/03_clean_data/River/ForestActivity_Cohort.fst
#       Cohort-weighted mean forest disturbance area for both rivers (FST)
#
# ══════════════════════════════════════════════════════════════════════════════


# ══════════════════════════════════════════════════════════════════════════════
# SECTION 2: LIBRARIES
# ══════════════════════════════════════════════════════════════════════════════

library(stringr)
library(sf)
library(dplyr)
library(ggplot2)
library(fst)
library(tidyr)
library(ggpubr)


# ══════════════════════════════════════════════════════════════════════════════
# SECTION 3: WORKING DIRECTORY
# ══════════════════════════════════════════════════════════════════════════════

# ── Working directory ──────────────────────────────────────────────────────
# Automatically detects the repository root based on the script location.
# No hardcoded path — works on any machine.
current_file <- rstudioapi::getActiveDocumentContext()$path
path_parts   <- unlist(strsplit(normalizePath(current_file, winslash = "/"), "/"))
target_index <- which(path_parts == "phd-chapter3-Atlantic-Salmon")
base_path    <- paste(path_parts[1:target_index], collapse = "/")
setwd(base_path)


# ══════════════════════════════════════════════════════════════════════════════
# SECTION 4: DATA IMPORT
# ══════════════════════════════════════════════════════════════════════════════

# ── Forest disturbance area — Saint-Jean ──────────────────────────────────────
# SOURCE: Derived from Quebec ecoforestry map (MFFP), clipped to watershed
# STATUS: Too large for GitHub — not included in this repository.
#         Generated by running: ForestActivity_STJ.R
pertu_stj <- read_fst(
  file.path(base_path,
            "R/01_derived_data/ForestActivities/ForestActivity_STJ.fst")) %>%
  dplyr::rename(year = EXERCICE) %>%
  dplyr::group_by(year) %>%
  dplyr::summarise(area = sum(area)) %>%
  dplyr::mutate(dplyr::across(c(year, area), as.numeric)) %>%
  tidyr::complete(year = full_seq(year, 1), fill = list(area = 0)) %>%
  dplyr::arrange(year)


# ── Forest disturbance area — Trinite ─────────────────────────────────────────
# SOURCE: Derived from Quebec ecoforestry map (MFFP), clipped to watershed
# STATUS: Too large for GitHub — not included in this repository.
#         Generated by running: ForestActivity_TRI.R
pertu_tri <- read_fst(
  file.path(base_path,
            "R/01_derived_data/ForestActivities/ForestActivity_TRI.fst")) %>%
  dplyr::rename(year = EXERCICE) %>%
  dplyr::group_by(year) %>%
  dplyr::summarise(area = sum(area)) %>%
  dplyr::mutate(dplyr::across(c(year, area), as.numeric)) %>%
  tidyr::complete(year = full_seq(year, 1), fill = list(area = 0)) %>%
  dplyr::arrange(year)


# ── Smolt age-class proportions ───────────────────────────────────────────────
# SOURCE: Quebec salmon monitoring program (MELCCFP)
# STATUS: Confidential — not included in this repository.
#         An example file with identical structure and simulated data is
#         available at the same path with the suffix _EXAMPLE.fst.
#         To request access, contact the MELCCFP once the thesis is published.
prop_smolt <- read_fst(
  file.path(base_path, "R/01_derived_data/Smolt_Proportions.fst"))


# ══════════════════════════════════════════════════════════════════════════════
# SECTION 6: FUNCTIONS
# ══════════════════════════════════════════════════════════════════════════════

# ── weighted_co ───────────────────────────────────────────────────────────────
# Purpose: Computes a cohort-weighted mean of an environmental variable for
#   each salmon cohort, weighting each year by the proportion of individuals
#   still in freshwater at that age.
# Parameters:
#   smolt_data  data frame with columns cohort, smolt_prop_2yr, smolt_prop_3yr,
#               smolt_prop_4yr, smolt_prop_5yr
#   env_data    data frame with columns year and area (annual env. variable)
# Returns: data frame with columns cohort and co_mean (weighted mean area),
#   restricted to cohorts with at least one non-NA age-class proportion.

weighted_co <- function(smolt_data, env_data) {
  
  years            <- unique(smolt_data$cohort)
  smolt_data$co_mean <- NA
  
  for (i in seq_along(years)) {
    
    smolt_data_i <- smolt_data %>%
      dplyr::filter(cohort == years[i])
    
    # Extract disturbance area for each freshwater year of the cohort.
    # A disturbance at time t is assumed to affect salmon at time t+1,
    # so year i maps to the first growth season (t_0).
    t_0 <- env_data %>%
      dplyr::filter(year %in% c(years[i]))     %>% dplyr::pull(area)
    t_1 <- env_data %>%
      dplyr::filter(year %in% c(years[i] + 1)) %>% dplyr::pull(area)
    t_2 <- env_data %>%
      dplyr::filter(year %in% c(years[i] + 2)) %>% dplyr::pull(area)
    t_3 <- env_data %>%
      dplyr::filter(year %in% c(years[i]))     %>% dplyr::pull(area)
    t_4 <- env_data %>%
      dplyr::filter(year %in% c(years[i] + 4)) %>% dplyr::pull(area)
    t_5 <- env_data %>%
      dplyr::filter(year %in% c(years[i] + 5)) %>% dplyr::pull(area)
    
    # Replace NA proportions with 0 only for the minority age classes
    # (2yr and 5yr); NA in 3yr or 4yr propagates to co_mean intentionally.
    p2 <- ifelse(is.na(smolt_data_i$smolt_prop_2yr), 0,
                 smolt_data_i$smolt_prop_2yr)
    p3 <- ifelse(is.na(smolt_data_i$smolt_prop_3yr), 0,
                 smolt_data_i$smolt_prop_3yr)
    p4 <- ifelse(is.na(smolt_data_i$smolt_prop_4yr), 0,
                 smolt_data_i$smolt_prop_4yr)
    p5 <- ifelse(is.na(smolt_data_i$smolt_prop_5yr), 0,
                 smolt_data_i$smolt_prop_5yr)
    
    # Weights decrease as cumulative smoltification removes individuals
    # from the freshwater population across ages.
    smolt_data$co_mean[i] <- weighted.mean(
      x = c(t_0, t_1, t_2, t_3, t_4, t_5),
      w = c(rep(1,                              length(t_0)),
            rep(1,                              length(t_1)),
            rep(max(c(0, 1 - p2)),              length(t_2)),
            rep(max(c(0, 1 - p2 - p3)),         length(t_3)),
            rep(max(c(0, 1 - p2 - p3 - p4)),    length(t_4)),
            rep(max(c(0, 1 - p2 - p3 - p4 - p5)), length(t_5))),
      na.rm = FALSE
    )
  }
  
  # Remove cohorts where all age-class proportions are NA, as replacing
  # all NAs with 0 would produce heavily biased weighted means.
  smolt_data <- smolt_data %>%
    dplyr::filter(!(is.na(smolt_data$smolt_prop_2yr) &
                      is.na(smolt_data$smolt_prop_3yr) &
                      is.na(smolt_data$smolt_prop_4yr) &
                      is.na(smolt_data$smolt_prop_5yr))) %>%
    dplyr::select(cohort, co_mean) %>%
    as.data.frame()
  
  return(smolt_data)
}


# ══════════════════════════════════════════════════════════════════════════════
# SECTION 7: MAIN SCRIPT
# ══════════════════════════════════════════════════════════════════════════════

# ── Split smolt proportions by river ─────────────────────────────────────────

prop_smolt_sub_sj <- prop_smolt %>%
  dplyr::filter(river == "stj")

prop_smolt_sub_tr <- prop_smolt %>%
  dplyr::filter(river == "tri")


# ── Compute cohort-weighted means ─────────────────────────────────────────────

# Since the exact timing of disturbances within the year is unknown,
# disturbances from year t are assumed to affect salmon starting at t+1.
weighted_co_sj <- weighted_co(
  smolt_data = prop_smolt_sub_sj, env_data = pertu_stj) %>%
  dplyr::rename(co_mean_forest = co_mean)

weighted_co_tr <- weighted_co(
  smolt_data = prop_smolt_sub_tr, env_data = pertu_tri) %>%
  dplyr::rename(co_mean_forest = co_mean)

ggarrange(
  ggplot(data = weighted_co_sj, aes(x = cohort, y = co_mean_forest)) +
    geom_line() +
    labs(title = "St. Jean"),
  ggplot(data = weighted_co_tr, aes(x = cohort, y = co_mean_forest)) +
    geom_line() +
    labs(title = "Trinite"),
  ncol = 1)


# ── Export ────────────────────────────────────────────────────────────────────

weighted_co_sj$river <- "stj"
weighted_co_tr$river <- "tri"

data_all <- bind_rows(weighted_co_sj, weighted_co_tr) %>%
  dplyr::select(river, cohort, everything())

write_fst(data_all,
          file.path(base_path, "R/03_clean_data/River/ForestActivity_Cohort.fst"))




