


# ==============================================================================
# Builds a zooplankton food availability index (PC1 from PCA) for Atlantic
# salmon sea-age classes (1SW, 2SW) for the Trinite and Saint-Jean rivers.
# Plankton biomass values at lags t, t+1, and t+2 are used as PCA inputs;
# PC1 orientation is aligned so that higher values indicate higher biomass.
#
# Inputs:
#   - Plankton_LabradorSea_tri_1SW.fst  : annual plankton biomass, TRI 1SW
#   - Plankton_LabradorSea_tri_2SW.fst  : annual plankton biomass, TRI 2SW
#   - Plankton_LabradorSea_stj_1SW.fst  : annual plankton biomass, STJ 1SW
#   - Plankton_LabradorSea_stj_2SW.fst  : annual plankton biomass, STJ 2SW
#
# Outputs:
#   - Food_Index_tri_1SW.fst  : plankton index (PC1), TRI 1SW (.fst)
#   - Food_Index_tri_2SW.fst  : plankton index (PC1), TRI 2SW (.fst)
#   - Food_Index_stj_1SW.fst  : plankton index (PC1), STJ 1SW (.fst)
#   - Food_Index_stj_2SW.fst  : plankton index (PC1), STJ 2SW (.fst)
# ==============================================================================




# ==============================================================================
# SECTION 1: LIBRARIES
# ==============================================================================

library(fst)
library(ggplot2)
library(ggrepel)
library(dplyr)
library(data.table)
library(tidyr)
library(corrplot)
library(ggcorrplot)
library(patchwork)
library(tidyverse)




# ==============================================================================
# SECTION 2: WORKING DIRECTORY
# ==============================================================================

# ── Working directory ──────────────────────────────────────────────────────────
# Automatically detects the repository root based on the script location.
# No hardcoded path — works on any machine.
current_file <- rstudioapi::getActiveDocumentContext()$path
path_parts   <- unlist(strsplit(normalizePath(current_file, winslash = "/"), "/"))
target_index <- which(path_parts == "phd-chapter3-Atlantic-Salmon")
base_path    <- paste(path_parts[1:target_index], collapse = "/")
setwd(base_path)




# ==============================================================================
# SECTION 3: DATA IMPORT
# ==============================================================================

# ── Plankton biomass files — TRI and STJ, 1SW and 2SW ─────────────────────────
# SOURCE: Derived from CPR (Continuous Plankton Recorder) survey data,
#         processed via GAM-based annual plankton index pipeline.
# STATUS: Too large for GitHub — not included in this repository.
#         Generated by running: plankton_gam_index.R

plankton_tri_1sw <- read_fst(
  file.path(base_path, "R/01_derived_data/Food_Availability/Plankton_LabradorSea_tri_1SW.fst")
)
plankton_tri_2sw <- read_fst(
  file.path(base_path, "R/01_derived_data/Food_Availability/Plankton_LabradorSea_tri_2SW.fst")
)
plankton_stj_1sw <- read_fst(
  file.path(base_path, "R/01_derived_data/Food_Availability/Plankton_LabradorSea_stj_1SW.fst")
)
plankton_stj_2sw <- read_fst(
  file.path(base_path, "R/01_derived_data/Food_Availability/Plankton_LabradorSea_stj_2SW.fst")
)




# ==============================================================================
# SECTION 4: FUNCTIONS
# ==============================================================================

# ── plot_cor ───────────────────────────────────────────────────────────────────
# Purpose: Produces a scatterplot with a linear smoother and Pearson correlation
#          annotation for two variables in a data frame.
# Parameters:
#   data  : data frame containing the variables to plot
#   var_x : character string, name of the x-axis variable
#   var_y : character string, name of the y-axis variable
#   title : optional character string for the plot title
# Returns: a ggplot object

plot_cor <- function(data, var_x, var_y, title = NULL) {
  
  r_val  <- cor(data[[var_x]], data[[var_y]])
  p_val  <- cor.test(data[[var_x]], data[[var_y]])$p.value
  
  p_label <- if (p_val < 0.001) "< 0.001" else as.character(round(p_val, 3))
  
  ggplot(data, aes(x = .data[[var_x]], y = .data[[var_y]])) +
    geom_point(color = "#2c7bb6", size = 2.5) +
    geom_smooth(method = "lm", color = "#d73027", fill = "#d73027",
                alpha = 0.1, linewidth = 1) +
    annotate("text",
             x = -Inf, y = Inf,
             hjust = -0.15, vjust = 1.5,
             label = paste0("r = ", round(r_val, 2), "\np = ", p_label),
             size = 4, fontface = "italic", color = "grey30") +
    labs(title = title, x = var_x, y = var_y) +
    theme_minimal(base_size = 13) +
    theme(plot.title = element_text(face = "bold", size = 11))
}




# ==============================================================================
# SECTION 5: MAIN SCRIPT — TRINITE (TRI)
# ==============================================================================

# ── TRI 1SW — PCA input preparation ───────────────────────────────────────────

# Select zooplankton biomass at t and t+1 for 1SW cohorts.
pca_data_tri_1sw_plk <- plankton_tri_1sw %>%
  dplyr::select(cohort, Plankton_t) %>%
  arrange(cohort) %>%
  mutate(Plankton_tp1 = lag(Plankton_t, n = 1)) %>%
  dplyr::select(-cohort) %>%
  na.omit()

cor_tri_1sw <- cor(pca_data_tri_1sw_plk, use = "complete.obs")

# Correlation check before running PCA.
p_cor_tri_1sw <- pca_data_tri_1sw_plk %>%
  ggplot(aes(x = Plankton_t, y = Plankton_tp1)) +
  geom_point(color = "#2c7bb6", size = 2.5) +
  geom_smooth(method = "lm", color = "#d73027", fill = "#d73027",
              alpha = 0.1, linewidth = 1) +
  annotate("text",
           x = -Inf, y = Inf,
           hjust = -0.15, vjust = 1.5,
           label = paste0("r = ", round(cor_tri_1sw[1, 2], 2),
                          "\np = ", round(cor.test(pca_data_tri_1sw_plk$Plankton_t,
                                                   pca_data_tri_1sw_plk$Plankton_tp1)$p.value, 3)),
           size = 4, fontface = "italic", color = "grey30") +
  labs(title = "TRI 1SW — Variable correlation",
       x = "Capelin biomass (t+1)", y = "Zooplankton biomass (t)") +
  theme_minimal(base_size = 13) +
  theme(plot.title = element_text(face = "bold"))
p_cor_tri_1sw


# ── TRI 1SW — PCA ─────────────────────────────────────────────────────────────

# cor = TRUE standardizes variables before computing the PCA.
pca_tri_1sw_plk <- princomp(pca_data_tri_1sw_plk, cor = TRUE)
summary(pca_tri_1sw_plk)
biplot(pca_tri_1sw_plk)

# PC1 sign is arbitrary; align it so higher values = higher biomass.
pc1_tri_1sw_plk      <- pca_tri_1sw_plk$scores[, 1]
biomass_mean_1sw_plk <- rowMeans(pca_data_tri_1sw_plk, na.rm = TRUE)
if (cor(pc1_tri_1sw_plk, biomass_mean_1sw_plk, use = "complete.obs") < 0) {
  pc1_tri_1sw_plk <- -pc1_tri_1sw_plk
}
pca_tri_1sw_plk$scores[, 1] <- pc1_tri_1sw_plk


# ── TRI 2SW — PCA input preparation ───────────────────────────────────────────

# Select zooplankton biomass at t, t+1, and t+2 for 2SW cohorts.
pca_data_tri_2sw_plk <- plankton_tri_2sw %>%
  dplyr::select(cohort, Plankton_t, Plankton_tp1) %>%
  arrange(cohort) %>%
  mutate(Plankton_tp2 = lag(Plankton_t, n = 2)) %>%
  dplyr::select(-cohort) %>%
  na.omit()

# Check pairwise correlations among all lag variables.
var_pairs <- combn(names(pca_data_tri_2sw_plk), 2, simplify = FALSE)

plots <- map(var_pairs, ~ plot_cor(
  data  = pca_data_tri_2sw_plk,
  var_x = .x[1],
  var_y = .x[2],
  title = paste0(.x[1], " ~ ", .x[2])
))

# Assemble correlation plots into a grid.
p_cor_tri_2sw_plk_all <- wrap_plots(plots, ncol = 3) +
  plot_annotation(
    title = "TRI 2SW — Zooplankton biomass lag correlations",
    theme = theme(plot.title = element_text(face = "bold", size = 14))
  )
p_cor_tri_2sw_plk_all


# ── TRI 2SW — PCA ─────────────────────────────────────────────────────────────

pca_tri_2sw_plk <- princomp(pca_data_tri_2sw_plk, cor = TRUE)
summary(pca_tri_2sw_plk)
biplot(pca_tri_2sw_plk)

# Compute an overall biomass proxy (mean across variables) to check PC1 orientation.
pc1_tri_2sw_plk      <- pca_tri_2sw_plk$scores[, 1]
biomass_mean_2sw_plk <- rowMeans(pca_data_tri_2sw_plk, na.rm = TRUE)
# Flip PC1 so that higher values correspond to higher biomass.
if (cor(pc1_tri_2sw_plk, biomass_mean_2sw_plk, use = "complete.obs") < 0) {
  pc1_tri_2sw_plk <- -pc1_tri_2sw_plk
}
pca_tri_2sw_plk$scores[, 1] <- pc1_tri_2sw_plk


# ── TRI — Assemble food availability index ────────────────────────────────────

# Combine 1SW and 2SW PC1 scores into a single data frame indexed by cohort.
food_index_tri <- data.frame(
  cohort       = plankton_tri_1sw$cohort[as.integer(rownames(pca_data_tri_1sw_plk))],
  river        = "tri",
  food_index_1 = pca_tri_1sw_plk$scores[, 1]
) %>%
  left_join(
    data.frame(
      cohort           = plankton_tri_1sw$cohort[
        as.integer(rownames(as.data.frame(pca_tri_1sw_plk$scores)))
      ],
      plankton_index_1 = pca_tri_1sw_plk$scores[, 1]
    ), by = "cohort"
  ) %>%
  left_join(
    data.frame(
      cohort           = plankton_tri_2sw$cohort[
        as.integer(rownames(as.data.frame(pca_tri_2sw_plk$scores)))
      ],
      plankton_index_2 = pca_tri_2sw_plk$scores[, 1]
    ), by = "cohort"
  )


# ── TRI — PCA biplots ─────────────────────────────────────────────────────────

arrow_scale <- 2

# Extract scores and loadings for TRI 1SW.
scores_tri_1sw_plk            <- as.data.frame(pca_tri_1sw_plk$scores)
scores_tri_1sw_plk$cohort     <- plankton_tri_1sw$cohort[
  as.integer(rownames(scores_tri_1sw_plk))
]
loadings_tri_1sw_plk          <- as.data.frame(pca_tri_1sw_plk$loadings[, 1:2])
loadings_tri_1sw_plk$Variable <- rownames(loadings_tri_1sw_plk)
var_explained_tri_1sw_plk     <- pca_tri_1sw_plk$sdev^2 / sum(pca_tri_1sw_plk$sdev^2)

# Extract scores and loadings for TRI 2SW.
scores_tri_2sw_plk            <- as.data.frame(pca_tri_2sw_plk$scores)
scores_tri_2sw_plk$cohort     <- plankton_tri_2sw$cohort[
  as.integer(rownames(scores_tri_2sw_plk))
]
loadings_tri_2sw_plk          <- as.data.frame(pca_tri_2sw_plk$loadings[, 1:2])
loadings_tri_2sw_plk$Variable <- rownames(loadings_tri_2sw_plk)
var_explained_tri_2sw_plk     <- pca_tri_2sw_plk$sdev^2 / sum(pca_tri_2sw_plk$sdev^2)

p_biplot_tri_1sw_plk <- ggplot(scores_tri_1sw_plk, aes(x = Comp.1, y = Comp.2)) +
  geom_hline(yintercept = 0, linetype = "dashed", color = "grey70") +
  geom_vline(xintercept = 0, linetype = "dashed", color = "grey70") +
  geom_point(aes(color = cohort), size = 2.5, alpha = 0.85) +
  geom_segment(
    data = loadings_tri_1sw_plk,
    aes(x = 0, y = 0,
        xend = Comp.1 * arrow_scale, yend = Comp.2 * arrow_scale),
    arrow = arrow(length = unit(0.25, "cm"), type = "closed"),
    color = "#d73027", linewidth = 0.8
  ) +
  geom_text_repel(
    data = loadings_tri_1sw_plk,
    aes(x = Comp.1 * arrow_scale, y = Comp.2 * arrow_scale, label = Variable),
    color = "#d73027", fontface = "bold", size = 3.5, box.padding = 0.4
  ) +
  scale_color_viridis_c(option = "plasma", name = "Cohort") +
  labs(
    title    = "TRI — 1SW zooplankton availability PCA",
    subtitle = "Zooplankton (t) and Zooplankton (t+1)",
    x        = paste0("PC1 (", round(var_explained_tri_1sw_plk[1] * 100, 1), "%)"),
    y        = paste0("PC2 (", round(var_explained_tri_1sw_plk[2] * 100, 1), "%)")
  ) +
  theme_minimal(base_size = 13) +
  theme(
    plot.title      = element_text(face = "bold"),
    plot.subtitle   = element_text(color = "grey40"),
    legend.position = "right"
  )
p_biplot_tri_1sw_plk

p_biplot_tri_2sw_plk <- ggplot(scores_tri_2sw_plk, aes(x = Comp.1, y = Comp.2)) +
  geom_hline(yintercept = 0, linetype = "dashed", color = "grey70") +
  geom_vline(xintercept = 0, linetype = "dashed", color = "grey70") +
  geom_point(aes(color = cohort), size = 2.5, alpha = 0.85) +
  geom_segment(
    data = loadings_tri_2sw_plk,
    aes(x = 0, y = 0,
        xend = Comp.1 * arrow_scale, yend = Comp.2 * arrow_scale),
    arrow = arrow(length = unit(0.25, "cm"), type = "closed"),
    color = "#d73027", linewidth = 0.8
  ) +
  geom_text_repel(
    data = loadings_tri_2sw_plk,
    aes(x = Comp.1 * arrow_scale, y = Comp.2 * arrow_scale, label = Variable),
    color = "#d73027", fontface = "bold", size = 3.5, box.padding = 0.4
  ) +
  scale_color_viridis_c(option = "plasma", name = "Cohort") +
  labs(
    title    = "TRI — 2SW zooplankton availability PCA",
    subtitle = "Zooplankton (t), Zooplankton (t+1) and Zooplankton (t+2)",
    x        = paste0("PC1 (", round(var_explained_tri_2sw_plk[1] * 100, 1), "%)"),
    y        = paste0("PC2 (", round(var_explained_tri_2sw_plk[2] * 100, 1), "%)")
  ) +
  theme_minimal(base_size = 13) +
  theme(
    plot.title      = element_text(face = "bold"),
    plot.subtitle   = element_text(color = "grey40"),
    legend.position = "right"
  )
p_biplot_tri_2sw_plk


# ── TRI — Plankton index time series ──────────────────────────────────────────

food_index_tri_long <- food_index_tri %>%
  pivot_longer(
    cols      = c(plankton_index_1, plankton_index_2),
    names_to  = "Index",
    values_to = "Value"
  )

p_index_tri <- ggplot(food_index_tri_long,
                      aes(x = cohort, y = Value, color = Index)) +
  geom_hline(yintercept = 0, linetype = "dashed", color = "grey70") +
  geom_line(linewidth = 1) +
  geom_point(size = 2.2) +
  scale_color_manual(
    values = c("plankton_index_1" = "#1f77b4", "plankton_index_2" = "#2ca02c"),
    labels = c("1SW — Zooplankton (t, t+1)", "2SW — Zooplankton (t, t+1, t+2)"),
    name   = NULL
  ) +
  labs(x = "Cohort year", y = "Zooplankton availability index (PC1)") +
  theme_minimal(base_size = 13) +
  theme(
    plot.title      = element_text(face = "bold"),
    plot.subtitle   = element_text(color = "grey40"),
    legend.position = "bottom"
  )
p_index_tri


# ── TRI — Save outputs ────────────────────────────────────────────────────────

food_index_tri_1sw <- food_index_tri %>%
  dplyr::select(cohort, river, plankton_index_1) %>%
  rename(plankton_index = plankton_index_1) %>%
  mutate(sw_type = "1SW")

write_fst(
  food_index_tri_1sw,
  file.path(base_path, "R/03_clean_data/Sea/Food_Index_tri_1SW.fst")
)

food_index_tri_2sw <- food_index_tri %>%
  dplyr::select(cohort, river, plankton_index_2) %>%
  rename(plankton_index = plankton_index_2) %>%
  mutate(sw_type = "2SW")

write_fst(
  food_index_tri_2sw,
  file.path(base_path, "R/03_clean_data/Sea/Food_Index_tri_2SW.fst")
)




# ==============================================================================
# SECTION 6: MAIN SCRIPT — SAINT-JEAN (STJ)
# ==============================================================================

# ── STJ 1SW — PCA input preparation ───────────────────────────────────────────

# Select zooplankton biomass at t and t+1 for 1SW cohorts.
pca_data_stj_1sw_plk <- plankton_stj_1sw %>%
  dplyr::select(cohort, Plankton_t) %>%
  arrange(cohort) %>%
  mutate(Plankton_tp1 = lag(Plankton_t, n = 1)) %>%
  dplyr::select(-cohort) %>%
  na.omit()

cor_stj_1sw <- cor(pca_data_stj_1sw_plk, use = "complete.obs")

# Correlation check before running PCA.
p_cor_stj_1sw <- pca_data_stj_1sw_plk %>%
  ggplot(aes(x = Plankton_t, y = Plankton_tp1)) +
  geom_point(color = "#2c7bb6", size = 2.5) +
  geom_smooth(method = "lm", color = "#d73027", fill = "#d73027",
              alpha = 0.1, linewidth = 1) +
  annotate("text",
           x = -Inf, y = Inf,
           hjust = -0.15, vjust = 1.5,
           label = paste0("r = ", round(cor_stj_1sw[1, 2], 2),
                          "\np = ", round(cor.test(pca_data_stj_1sw_plk$Plankton_t,
                                                   pca_data_stj_1sw_plk$Plankton_tp1)$p.value, 3)),
           size = 4, fontface = "italic", color = "grey30") +
  labs(title = "STJ 1SW — Variable correlation",
       x = "Zooplankton biomass (t)", y = "Zooplankton biomass (t+1)") +
  theme_minimal(base_size = 13) +
  theme(plot.title = element_text(face = "bold"))
p_cor_stj_1sw


# ── STJ 1SW — PCA ─────────────────────────────────────────────────────────────

pca_stj_1sw_plk <- princomp(pca_data_stj_1sw_plk, cor = TRUE)
summary(pca_stj_1sw_plk)
biplot(pca_stj_1sw_plk)

# PC1 sign is arbitrary; align it so higher values = higher biomass.
pc1_stj_1sw_plk          <- pca_stj_1sw_plk$scores[, 1]
biomass_mean_stj_1sw_plk <- rowMeans(pca_data_stj_1sw_plk, na.rm = TRUE)
if (cor(pc1_stj_1sw_plk, biomass_mean_stj_1sw_plk, use = "complete.obs") < 0) {
  pc1_stj_1sw_plk <- -pc1_stj_1sw_plk
}
pca_stj_1sw_plk$scores[, 1] <- pc1_stj_1sw_plk


# ── STJ 2SW — PCA input preparation ───────────────────────────────────────────

# Select zooplankton biomass at t, t+1, and t+2 for 2SW cohorts.
pca_data_stj_2sw_plk <- plankton_stj_2sw %>%
  dplyr::select(cohort, Plankton_t, Plankton_tp1) %>%
  arrange(cohort) %>%
  mutate(Plankton_tp2 = lag(Plankton_t, n = 2)) %>%
  dplyr::select(-cohort) %>%
  na.omit()

# Check pairwise correlations among all lag variables.
var_pairs_stj <- combn(names(pca_data_stj_2sw_plk), 2, simplify = FALSE)

plots_stj <- map(var_pairs_stj, ~ plot_cor(
  data  = pca_data_stj_2sw_plk,
  var_x = .x[1],
  var_y = .x[2],
  title = paste0(.x[1], " ~ ", .x[2])
))

p_cor_stj_2sw_plk_all <- wrap_plots(plots_stj, ncol = 3) +
  plot_annotation(
    title = "STJ 2SW — Zooplankton biomass lag correlations",
    theme = theme(plot.title = element_text(face = "bold", size = 14))
  )
p_cor_stj_2sw_plk_all


# ── STJ 2SW — PCA ─────────────────────────────────────────────────────────────

pca_stj_2sw_plk <- princomp(pca_data_stj_2sw_plk, cor = TRUE)
summary(pca_stj_2sw_plk)
biplot(pca_stj_2sw_plk)

# Flip PC1 if needed so that higher values correspond to higher biomass.
pc1_stj_2sw_plk          <- pca_stj_2sw_plk$scores[, 1]
biomass_mean_stj_2sw_plk <- rowMeans(pca_data_stj_2sw_plk, na.rm = TRUE)
if (cor(pc1_stj_2sw_plk, biomass_mean_stj_2sw_plk, use = "complete.obs") < 0) {
  pc1_stj_2sw_plk <- -pc1_stj_2sw_plk
}
pca_stj_2sw_plk$scores[, 1] <- pc1_stj_2sw_plk


# ── STJ — Assemble food availability index ────────────────────────────────────

food_index_stj <- data.frame(
  cohort           = plankton_stj_1sw$cohort[as.integer(rownames(pca_data_stj_1sw_plk))],
  river            = "stj",
  plankton_index_1 = pca_stj_1sw_plk$scores[, 1]
) %>%
  left_join(
    data.frame(
      cohort           = plankton_stj_2sw$cohort[
        as.integer(rownames(as.data.frame(pca_stj_2sw_plk$scores)))
      ],
      plankton_index_2 = pca_stj_2sw_plk$scores[, 1]
    ), by = "cohort"
  )


# ── STJ — PCA biplots ─────────────────────────────────────────────────────────

# Extract scores and loadings for STJ 1SW.
scores_stj_1sw_plk            <- as.data.frame(pca_stj_1sw_plk$scores)
scores_stj_1sw_plk$cohort     <- plankton_stj_1sw$cohort[
  as.integer(rownames(scores_stj_1sw_plk))
]
loadings_stj_1sw_plk          <- as.data.frame(pca_stj_1sw_plk$loadings[, 1:2])
loadings_stj_1sw_plk$Variable <- rownames(loadings_stj_1sw_plk)
var_explained_stj_1sw_plk     <- pca_stj_1sw_plk$sdev^2 / sum(pca_stj_1sw_plk$sdev^2)

# Extract scores and loadings for STJ 2SW.
scores_stj_2sw_plk            <- as.data.frame(pca_stj_2sw_plk$scores)
scores_stj_2sw_plk$cohort     <- plankton_stj_2sw$cohort[
  as.integer(rownames(scores_stj_2sw_plk))
]
loadings_stj_2sw_plk          <- as.data.frame(pca_stj_2sw_plk$loadings[, 1:2])
loadings_stj_2sw_plk$Variable <- rownames(loadings_stj_2sw_plk)
var_explained_stj_2sw_plk     <- pca_stj_2sw_plk$sdev^2 / sum(pca_stj_2sw_plk$sdev^2)

p_biplot_stj_1sw_plk <- ggplot(scores_stj_1sw_plk, aes(x = Comp.1, y = Comp.2)) +
  geom_hline(yintercept = 0, linetype = "dashed", color = "grey70") +
  geom_vline(xintercept = 0, linetype = "dashed", color = "grey70") +
  geom_point(aes(color = cohort), size = 2.5, alpha = 0.85) +
  geom_segment(
    data = loadings_stj_1sw_plk,
    aes(x = 0, y = 0,
        xend = Comp.1 * arrow_scale, yend = Comp.2 * arrow_scale),
    arrow = arrow(length = unit(0.25, "cm"), type = "closed"),
    color = "#d73027", linewidth = 0.8
  ) +
  geom_text_repel(
    data = loadings_stj_1sw_plk,
    aes(x = Comp.1 * arrow_scale, y = Comp.2 * arrow_scale, label = Variable),
    color = "#d73027", fontface = "bold", size = 3.5, box.padding = 0.4
  ) +
  scale_color_viridis_c(option = "plasma", name = "Cohort") +
  labs(
    title    = "STJ — 1SW zooplankton availability PCA",
    subtitle = "Zooplankton (t) and Zooplankton (t+1)",
    x        = paste0("PC1 (", round(var_explained_stj_1sw_plk[1] * 100, 1), "%)"),
    y        = paste0("PC2 (", round(var_explained_stj_1sw_plk[2] * 100, 1), "%)")
  ) +
  theme_minimal(base_size = 13) +
  theme(
    plot.title      = element_text(face = "bold"),
    plot.subtitle   = element_text(color = "grey40"),
    legend.position = "right"
  )
p_biplot_stj_1sw_plk

p_biplot_stj_2sw_plk <- ggplot(scores_stj_2sw_plk, aes(x = Comp.1, y = Comp.2)) +
  geom_hline(yintercept = 0, linetype = "dashed", color = "grey70") +
  geom_vline(xintercept = 0, linetype = "dashed", color = "grey70") +
  geom_point(aes(color = cohort), size = 2.5, alpha = 0.85) +
  geom_segment(
    data = loadings_stj_2sw_plk,
    aes(x = 0, y = 0,
        xend = Comp.1 * arrow_scale, yend = Comp.2 * arrow_scale),
    arrow = arrow(length = unit(0.25, "cm"), type = "closed"),
    color = "#d73027", linewidth = 0.8
  ) +
  geom_text_repel(
    data = loadings_stj_2sw_plk,
    aes(x = Comp.1 * arrow_scale, y = Comp.2 * arrow_scale, label = Variable),
    color = "#d73027", fontface = "bold", size = 3.5, box.padding = 0.4
  ) +
  scale_color_viridis_c(option = "plasma", name = "Cohort") +
  labs(
    title    = "STJ — 2SW zooplankton availability PCA",
    subtitle = "Zooplankton (t), Zooplankton (t+1) and Zooplankton (t+2)",
    x        = paste0("PC1 (", round(var_explained_stj_2sw_plk[1] * 100, 1), "%)"),
    y        = paste0("PC2 (", round(var_explained_stj_2sw_plk[2] * 100, 1), "%)")
  ) +
  theme_minimal(base_size = 13) +
  theme(
    plot.title      = element_text(face = "bold"),
    plot.subtitle   = element_text(color = "grey40"),
    legend.position = "right"
  )
p_biplot_stj_2sw_plk


# ── STJ — Plankton index time series ──────────────────────────────────────────

food_index_stj_long <- food_index_stj %>%
  pivot_longer(
    cols      = c(plankton_index_1, plankton_index_2),
    names_to  = "Index",
    values_to = "Value"
  )

p_index_stj <- ggplot(food_index_stj_long,
                      aes(x = cohort, y = Value, color = Index)) +
  geom_hline(yintercept = 0, linetype = "dashed", color = "grey70") +
  geom_line(linewidth = 1) +
  geom_point(size = 2.2) +
  scale_color_manual(
    values = c("plankton_index_1" = "#1f77b4", "plankton_index_2" = "#2ca02c"),
    labels = c("1SW — Zooplankton (t, t+1)", "2SW — Zooplankton (t, t+1, t+2)"),
    name   = NULL
  ) +
  labs(x = "Cohort year", y = "Zooplankton availability index (PC1)") +
  theme_minimal(base_size = 13) +
  theme(
    plot.title      = element_text(face = "bold"),
    plot.subtitle   = element_text(color = "grey40"),
    legend.position = "bottom"
  )
p_index_stj


# ── STJ — Save outputs ────────────────────────────────────────────────────────

food_index_stj_1sw <- food_index_stj %>%
  dplyr::select(cohort, river, plankton_index_1) %>%
  rename(plankton_index = plankton_index_1) %>%
  mutate(sw_type = "1SW")

write_fst(
  food_index_stj_1sw,
  file.path(base_path, "R/03_clean_data/Sea/Food_Index_stj_1SW.fst")
)

food_index_stj_2sw <- food_index_stj %>%
  dplyr::select(cohort, river, plankton_index_2) %>%
  rename(plankton_index = plankton_index_2) %>%
  mutate(sw_type = "2SW")

write_fst(
  food_index_stj_2sw,
  file.path(base_path, "R/03_clean_data/Sea/Food_Index_stj_2SW.fst")
)







