

# ══════════════════════════════════════════════════════════════════════════════
# SECTION 1: HEADER
# ══════════════════════════════════════════════════════════════════════════════
#
# Computes cohort-weighted discharge metrics (mean, median, variance, 75th
# percentile, minimum 30-day average) during the growth and emergence periods
# for salmon cohorts of the Saint-Jean and Trinite rivers.
#
# Inputs:
#   - R/00_raw_data/Temperature_Discharge_River/
#       CEQEAU_Temperature_Discharge_1979_2024_SJ.csv
#       CEQEAU_Temperature_Discharge_1979_2024_TR.csv
#       Simulated daily discharge for Saint-Jean and Trinite rivers (CSV)
#   - R/01_derived_data/Smolt_Proportions.fst
#       Smolt age-class proportions by river and cohort year (FST)
#   - R/01_derived_data/GrowthPeriods/Growth_Periods_STJ.fst
#       Annual growth period (start/end DOY) for Saint-Jean (FST)
#   - R/01_derived_data/GrowthPeriods/Growth_Periods_TRI.fst
#       Annual growth period (start/end DOY) for Trinite (FST)
#
# Outputs:
#   - R/03_clean_data/River/River_Discharge.fst
#       Cohort-level discharge metrics for both rivers (FST)
#
# ══════════════════════════════════════════════════════════════════════════════


# ══════════════════════════════════════════════════════════════════════════════
# SECTION 2: LIBRARIES
# ══════════════════════════════════════════════════════════════════════════════

library(fst)
library(dplyr)
library(lubridate)
library(ggplot2)
library(stringr)
library(ggpubr)
library(tidyr)
library(modi)
library(zoo)


# ══════════════════════════════════════════════════════════════════════════════
# SECTION 3: WORKING DIRECTORY
# ══════════════════════════════════════════════════════════════════════════════

# ── Working directory ──────────────────────────────────────────────────────
# Automatically detects the repository root based on the script location.
# No hardcoded path — works on any machine.
current_file <- rstudioapi::getActiveDocumentContext()$path
path_parts   <- unlist(strsplit(normalizePath(current_file, winslash = "/"), "/"))
target_index <- which(path_parts == "phd-chapter3-Atlantic-Salmon")
base_path    <- paste(path_parts[1:target_index], collapse = "/")
setwd(base_path)


# ══════════════════════════════════════════════════════════════════════════════
# SECTION 4: DATA IMPORT
# ══════════════════════════════════════════════════════════════════════════════

# ── Simulated daily discharge — Saint-Jean ────────────────────────────────────
# SOURCE: CEQEAU hydrological model outputs
# STATUS: Confidential — not included in this repository.
#         An example file with identical structure and simulated data is
#         available at the same path with the suffix _EXAMPLE.csv.
#         To request access, contact the data provider once the thesis
#         is published.
disch_stj <- read.csv(
  file.path(base_path,
            "R/00_raw_data/Temperature_Discharge_River",
            "CEQEAU_Temperature_Discharge_1979_2024_SJ.csv"))


# ── Simulated daily discharge — Trinite ───────────────────────────────────────
# SOURCE: CEQEAU hydrological model outputs
# STATUS: Confidential — not included in this repository.
#         An example file with identical structure and simulated data is
#         available at the same path with the suffix _EXAMPLE.csv.
#         To request access, contact the data provider once the thesis
#         is published.
disch_tri <- read.csv(
  file.path(base_path,
            "R/00_raw_data/Temperature_Discharge_River",
            "CEQEAU_Temperature_Discharge_1979_2024_TR.csv"))


# ── Smolt age-class proportions ───────────────────────────────────────────────
# SOURCE: Quebec salmon monitoring program (MELCCFP)
# STATUS: Confidential — not included in this repository.
#         An example file with identical structure and simulated data is
#         available at the same path with the suffix _EXAMPLE.fst.
#         To request access, contact the MELCCFP once the thesis is published.
prop_smolt <- read_fst(
  file.path(base_path, "R/01_derived_data/Smolt_Proportions.fst"))


# ── Annual growth periods ─────────────────────────────────────────────────────
# SOURCE: Derived from temperature data
# STATUS: Too large for GitHub — not included in this repository.
#         Generated by running: Growth_Periods_STJ.R / Growth_Periods_TRI.R
gr_period_stj <- read_fst(
  file.path(base_path,
            "R/01_derived_data/Growth_Periods_StJean.fst"))
gr_period_tri <- read_fst(
  file.path(base_path,
            "R/01_derived_data/Growth_Periods_Trinite.fst"))


# ══════════════════════════════════════════════════════════════════════════════
# SECTION 5: CONFIGURATION
# ══════════════════════════════════════════════════════════════════════════════

# Fixed DOY bounds for hatching and emergence periods (same across all years)
hatch_start_doy <- 98   # Start DOY of the hatching period
hatch_end_doy   <- 136  # End DOY of the hatching period
em_start_doy    <- 137  # Start DOY of the emergence period
em_end_doy      <- 154  # End DOY of the emergence period

annee <- 1994  # Reference year used for exploratory discharge plots


# ══════════════════════════════════════════════════════════════════════════════
# SECTION 6: FUNCTIONS
# ══════════════════════════════════════════════════════════════════════════════

# ── weighted_median ───────────────────────────────────────────────────────────
# Purpose: Computes a weighted median by ordering values and finding the point
#   where cumulative weights reach 0.5.
# Parameters:
#   x   numeric vector of values
#   w   numeric vector of weights (same length as x)
# Returns: scalar weighted median value.

weighted_median <- function(x, w) {
  
  # Remove pairs where either value or weight is NA
  keep <- !is.na(x) & !is.na(w)
  x    <- x[keep]
  w    <- w[keep]
  
  # Sort by value before computing cumulative weights
  o <- order(x)
  x <- x[o]
  w <- w[o]
  
  cum_w <- cumsum(w) / sum(w)
  x[which(cum_w >= 0.5)[1]]
}


# ── weighted_co_disch ─────────────────────────────────────────────────────────
# Purpose: Computes cohort-weighted mean, median, and variance of daily
#   discharge during the growth period, weighting each freshwater year by the
#   proportion of the cohort still present in the river at that age.
# Parameters:
#   smolt_data      data frame with columns cohort, smolt_prop_2yr–5yr
#   discharge_data  data frame with columns year, doy, simulated_discharge_m3s
#   periods         data frame with columns year, start_doy, end_doy
# Returns: data frame with columns cohort, co_mean_disch, co_median_disch,
#   co_var_disch, restricted to cohorts with at least one non-NA proportion.

weighted_co_disch <- function(smolt_data, discharge_data, periods) {
  
  years                      <- unique(smolt_data$cohort)
  smolt_data$co_mean_disch   <- NA
  smolt_data$co_median_disch <- NA
  smolt_data$co_var_disch    <- NA
  
  for (i in seq_along(years)) {
    
    smolt_data_i <- smolt_data %>% filter(cohort == years[i])
    
    # i is the egg-deposition year; growth season t+0 maps to calendar year i+1
    extract_discharge <- function(offset) {
      period_i <- periods %>%
        filter(year == smolt_data_i$cohort + offset)
      if (nrow(period_i) == 0 ||
          is.na(period_i$start_doy) ||
          is.na(period_i$end_doy)) return(NA_real_)
      if (!years[i] + offset %in% discharge_data$year) return(NA_real_)
      vals <- discharge_data %>%
        dplyr::filter(year  == years[i] + offset,
                      doy   >= period_i$start_doy,
                      doy   <= period_i$end_doy) %>%
        dplyr::pull(simulated_discharge_m3s)
      if (length(vals) == 0) NA_real_ else vals
    }
    
    t_0 <- extract_discharge(1)
    t_1 <- extract_discharge(2)
    t_2 <- extract_discharge(3)
    t_3 <- extract_discharge(4)
    t_4 <- extract_discharge(5)
    t_5 <- extract_discharge(6)
    
    p2 <- ifelse(is.na(smolt_data_i$smolt_prop_2yr), 0,
                 smolt_data_i$smolt_prop_2yr)
    p3 <- ifelse(is.na(smolt_data_i$smolt_prop_3yr), 0,
                 smolt_data_i$smolt_prop_3yr)
    p4 <- ifelse(is.na(smolt_data_i$smolt_prop_4yr), 0,
                 smolt_data_i$smolt_prop_4yr)
    p5 <- ifelse(is.na(smolt_data_i$smolt_prop_5yr), 0,
                 smolt_data_i$smolt_prop_5yr)
    
    x_all <- c(t_0, t_1, t_2, t_3, t_4, t_5)
    w_all <- c(
      rep(1,                              length(t_0)),
      rep(1,                              length(t_1)),
      rep(max(c(0, 1 - p2)),              length(t_2)),
      rep(max(c(0, 1 - p2 - p3)),         length(t_3)),
      rep(max(c(0, 1 - p2 - p3 - p4)),    length(t_4)),
      rep(max(c(0, 1 - p2 - p3 - p4 - p5)), length(t_5))
    )
    
    smolt_data$co_mean_disch[i]   <- weighted.mean(
      x = x_all, w = w_all, na.rm = FALSE)
    smolt_data$co_median_disch[i] <- weighted_median(
      x = x_all, w = w_all)
    
    if (length(x_all) > 0 && length(w_all) > 0) {
      smolt_data$co_var_disch[i] <- weighted.var(
        x = x_all, w = w_all, na.rm = FALSE)
    } else {
      smolt_data$co_var_disch[i] <- NA
    }
  }
  
  smolt_data %>%
    dplyr::filter(!(is.na(smolt_data$smolt_prop_2yr) &
                      is.na(smolt_data$smolt_prop_3yr) &
                      is.na(smolt_data$smolt_prop_4yr) &
                      is.na(smolt_data$smolt_prop_5yr))) %>%
    dplyr::select(cohort, co_mean_disch, co_median_disch, co_var_disch) %>%
    as.data.frame()
}


# ── weighted_co_disch_75qt ────────────────────────────────────────────────────
# Purpose: Computes the cohort-weighted mean of the annual 75th-percentile
#   discharge during the growth period, following Obedzinski et al. (2018).
# Parameters:
#   smolt_data      data frame with columns cohort, smolt_prop_2yr–5yr
#   discharge_data  data frame with columns year, doy, simulated_discharge_m3s
#   periods         data frame with columns year, start_doy, end_doy
# Returns: data frame with columns cohort and co_mean_disch.

weighted_co_disch_75qt <- function(smolt_data, discharge_data, periods) {
  
  years                    <- unique(smolt_data$cohort)
  smolt_data$co_mean_disch <- NA
  
  for (i in seq_along(years)) {
    
    smolt_data_i <- smolt_data %>% filter(cohort == years[i])
    
    extract_qt75 <- function(offset) {
      period_i <- periods %>%
        filter(year == smolt_data_i$cohort + offset)
      if (nrow(period_i) == 0 ||
          is.na(period_i$start_doy) ||
          is.na(period_i$end_doy)) return(NA_real_)
      if (!years[i] + offset %in% discharge_data$year) return(NA_real_)
      vals <- discharge_data %>%
        dplyr::filter(year  == years[i] + offset,
                      doy   >= period_i$start_doy,
                      doy   <= period_i$end_doy) %>%
        dplyr::pull(simulated_discharge_m3s)
      if (length(vals) == 0) NA_real_ else as.numeric(quantile(vals, 0.75))
    }
    
    t_0 <- extract_qt75(1)
    t_1 <- extract_qt75(2)
    t_2 <- extract_qt75(3)
    t_3 <- extract_qt75(4)
    t_4 <- extract_qt75(5)
    t_5 <- extract_qt75(6)
    
    p2 <- ifelse(is.na(smolt_data_i$smolt_prop_2yr), 0,
                 smolt_data_i$smolt_prop_2yr)
    p3 <- ifelse(is.na(smolt_data_i$smolt_prop_3yr), 0,
                 smolt_data_i$smolt_prop_3yr)
    p4 <- ifelse(is.na(smolt_data_i$smolt_prop_4yr), 0,
                 smolt_data_i$smolt_prop_4yr)
    p5 <- ifelse(is.na(smolt_data_i$smolt_prop_5yr), 0,
                 smolt_data_i$smolt_prop_5yr)
    
    smolt_data$co_mean_disch[i] <- weighted.mean(
      x = c(t_0, t_1, t_2, t_3, t_4, t_5),
      w = c(rep(1,                              length(t_0)),
            rep(1,                              length(t_1)),
            rep(max(c(0, 1 - p2)),              length(t_2)),
            rep(max(c(0, 1 - p2 - p3)),         length(t_3)),
            rep(max(c(0, 1 - p2 - p3 - p4)),    length(t_4)),
            rep(max(c(0, 1 - p2 - p3 - p4 - p5)), length(t_5))),
      na.rm = FALSE
    )
  }
  
  smolt_data %>%
    dplyr::filter(!(is.na(smolt_data$smolt_prop_2yr) &
                      is.na(smolt_data$smolt_prop_3yr) &
                      is.na(smolt_data$smolt_prop_4yr) &
                      is.na(smolt_data$smolt_prop_5yr))) %>%
    dplyr::select(cohort, co_mean_disch) %>%
    as.data.frame()
}


# ── weighted_co_disch (30-day minimum) ───────────────────────────────────────
# Purpose: Computes the cohort-weighted mean of the annual minimum 30-day
#   average discharge during the growth period, following
#   Obedzinski et al. (2018). For each year, all possible 30-day rolling
#   windows within the growth period are computed, and the minimum window
#   mean is taken as the annual value.
# Parameters:
#   smolt_data      data frame with columns cohort, smolt_prop_2yr–5yr
#   discharge_data  data frame with columns year, doy, simulated_discharge_m3s
#   periods         data frame with columns year, start_doy, end_doy
# Returns: data frame with columns cohort and co_30d_mean_disch.

weighted_co_disch_30d <- function(smolt_data, discharge_data, periods) {
  
  years                        <- unique(smolt_data$cohort)
  smolt_data$co_30d_mean_disch <- NA
  
  for (i in seq_along(years)) {
    
    smolt_data_i <- smolt_data %>% filter(cohort == years[i])
    
    extract_30d_min <- function(offset) {
      period_i <- periods %>%
        filter(year == smolt_data_i$cohort + offset)
      if (nrow(period_i) == 0 ||
          is.na(period_i$start_doy) ||
          is.na(period_i$end_doy)) return(NA_real_)
      if (!years[i] + offset %in% discharge_data$year) return(NA_real_)
      vals <- discharge_data %>%
        dplyr::filter(year  == years[i] + offset,
                      doy   >= period_i$start_doy,
                      doy   <= period_i$end_doy) %>%
        dplyr::pull(simulated_discharge_m3s)
      if (length(vals) == 0) return(NA_real_)
      # Rolling 30-day windows; value assigned to the last day of each window
      rolled <- rollapply(vals, width = 30, FUN = mean, fill = NA,
                          align = "right")
      # Remove leading NAs from windows shorter than 30 days, then take min
      min(as.numeric(na.omit(rolled)))
    }
    
    t_0 <- extract_30d_min(1)
    t_1 <- extract_30d_min(2)
    t_2 <- extract_30d_min(3)
    t_3 <- extract_30d_min(4)
    t_4 <- extract_30d_min(5)
    t_5 <- extract_30d_min(6)
    
    p2 <- ifelse(is.na(smolt_data_i$smolt_prop_2yr), 0,
                 smolt_data_i$smolt_prop_2yr)
    p3 <- ifelse(is.na(smolt_data_i$smolt_prop_3yr), 0,
                 smolt_data_i$smolt_prop_3yr)
    p4 <- ifelse(is.na(smolt_data_i$smolt_prop_4yr), 0,
                 smolt_data_i$smolt_prop_4yr)
    p5 <- ifelse(is.na(smolt_data_i$smolt_prop_5yr), 0,
                 smolt_data_i$smolt_prop_5yr)
    
    smolt_data$co_30d_mean_disch[i] <- weighted.mean(
      x = c(t_0, t_1, t_2, t_3, t_4, t_5),
      w = c(rep(1,                              length(t_0)),
            rep(1,                              length(t_1)),
            rep(max(c(0, 1 - p2)),              length(t_2)),
            rep(max(c(0, 1 - p2 - p3)),         length(t_3)),
            rep(max(c(0, 1 - p2 - p3 - p4)),    length(t_4)),
            rep(max(c(0, 1 - p2 - p3 - p4 - p5)), length(t_5))),
      na.rm = FALSE
    )
  }
  
  smolt_data %>%
    dplyr::filter(!(is.na(smolt_data$smolt_prop_2yr) &
                      is.na(smolt_data$smolt_prop_3yr) &
                      is.na(smolt_data$smolt_prop_4yr) &
                      is.na(smolt_data$smolt_prop_5yr))) %>%
    dplyr::select(cohort, co_30d_mean_disch) %>%
    as.data.frame()
}


# ══════════════════════════════════════════════════════════════════════════════
# SECTION 7: MAIN SCRIPT
# ══════════════════════════════════════════════════════════════════════════════

# ── Reformat discharge data ───────────────────────────────────────────────────

# Standardize column names across both rivers before further processing
colnames(disch_stj)[
  which(colnames(disch_stj) == "Observed.Discharge..m3.s.")] <-
  "Observed_Discharge_m3s"
colnames(disch_stj)[
  which(colnames(disch_stj) == "Simulated.Discharge..m3.s.")] <-
  "Simulated_Discharge_m3s"
colnames(disch_stj)[
  which(colnames(disch_stj) == "Tw..degree.C.")] <-
  "Temperature_C"

colnames(disch_tri)[
  which(colnames(disch_tri) == "Observed.Discharge..RatingCurve...m3.s.")] <-
  "Observed_Discharge_m3s"
colnames(disch_tri)[
  which(colnames(disch_tri) == "Simulated.Discharge..m3.s.")] <-
  "Simulated_Discharge_m3s"
colnames(disch_tri)[
  which(colnames(disch_tri) == "Simulated.Tw..degree.C.")] <-
  "Temperature_C"

colnames(disch_stj) <- tolower(colnames(disch_stj))
colnames(disch_tri) <- tolower(colnames(disch_tri))

# Parse date strings — temporarily set locale to C to ensure English month
# abbreviations are recognised regardless of the user's system locale
old_locale <- Sys.getlocale("LC_TIME")
Sys.setlocale("LC_TIME", "C")
disch_stj$date <- as.Date(disch_stj$date, format = "%d-%b-%Y")
disch_tri$date <- as.Date(disch_tri$date, format = "%d-%b-%Y")
Sys.setlocale("LC_TIME", old_locale)

# Keep only the columns needed downstream
disch_stj <- subset(disch_stj, select = c("date", "simulated_discharge_m3s"))
disch_tri <- subset(disch_tri, select = c("date", "simulated_discharge_m3s"))

# Derive temporal columns used for period filtering
disch_stj$year  <- year(disch_stj$date)
disch_stj$month <- month(disch_stj$date)
disch_stj$day   <- day(disch_stj$date)
disch_stj$doy   <- yday(disch_stj$date)

disch_tri$year  <- year(disch_tri$date)
disch_tri$month <- month(disch_tri$date)
disch_tri$day   <- day(disch_tri$date)
disch_tri$doy   <- yday(disch_tri$date)

# Exploratory plots to visually check discharge series for a reference year
ggplot(data = disch_stj %>%
         filter((month >= 5 & month <= 10) & year == annee),
       aes(x = date, y = simulated_discharge_m3s)) +
  geom_line()

ggplot(data = disch_tri %>%
         filter((month >= 6 & month <= 9) & year == annee),
       aes(x = date, y = simulated_discharge_m3s)) +
  geom_line()


# ── Build period lookup tables and split smolt proportions ────────────────────

# Fixed-DOY periods are the same for all years; built from the growth period
# year index so that the lookup structure matches that of gr_period_*
hatch_period <- data.frame(
  year      = sort(unique(gr_period_stj$year)),
  start_doy = hatch_start_doy,
  end_doy   = hatch_end_doy
)

em_period <- data.frame(
  year      = sort(unique(gr_period_stj$year)),
  start_doy = em_start_doy,
  end_doy   = em_end_doy
)

prop_smolt_sub_stj <- prop_smolt %>% dplyr::filter(river == "stj")
prop_smolt_sub_tri <- prop_smolt %>% dplyr::filter(river == "tri")


# ── Cohort mean, median, and variance discharge during the growth season ───────

weighted_co_season_stj <- weighted_co_disch(
  smolt_data     = prop_smolt_sub_stj,
  discharge_data = disch_stj,
  periods        = gr_period_stj
) %>%
  rename(co_gr_mean_disc   = co_mean_disch,
         co_gr_median_disc = co_median_disch,
         co_gr_var_disc    = co_var_disch)

weighted_co_season_tri <- weighted_co_disch(
  smolt_data     = prop_smolt_sub_tri,
  discharge_data = disch_tri,
  periods        = gr_period_tri
) %>%
  rename(co_gr_mean_disc   = co_mean_disch,
         co_gr_median_disc = co_median_disch,
         co_gr_var_disc    = co_var_disch)

ggarrange(
  ggarrange(
    ggplot(data = weighted_co_season_stj,
           aes(x = cohort, y = co_gr_mean_disc)) +
      geom_point() + geom_line() + labs(title = "St-Jean River"),
    ggplot(data = weighted_co_season_tri,
           aes(x = cohort, y = co_gr_mean_disc)) +
      geom_point() + geom_line() + labs(title = "Trinite River"),
    ncol = 2),
  ggarrange(
    ggplot(data = weighted_co_season_stj,
           aes(x = cohort, y = co_gr_median_disc)) +
      geom_point() + geom_line() + labs(title = "St-Jean River"),
    ggplot(data = weighted_co_season_tri,
           aes(x = cohort, y = co_gr_median_disc)) +
      geom_point() + geom_line() + labs(title = "Trinite River"),
    ncol = 2),
  ncol = 1)

ggarrange(
  ggplot(data = weighted_co_season_stj,
         aes(x = cohort, y = co_gr_var_disc)) +
    geom_point() + geom_line() + labs(title = "St-Jean River"),
  ggplot(data = weighted_co_season_tri,
         aes(x = cohort, y = co_gr_var_disc)) +
    geom_point() + geom_line() + labs(title = "Trinite River"),
  ncol = 2)


# ── Discharge statistics during the emergence period ─────────────────────────

# One value per cohort year, no smolt-weighting needed here
emergence_stj <- disch_stj %>%
  dplyr::filter(doy >= unique(em_period$start_doy),
                doy <= unique(em_period$end_doy)) %>%
  dplyr::rename(cohort = year) %>%
  dplyr::group_by(cohort) %>%
  dplyr::summarise(em_mean_disc   = mean(simulated_discharge_m3s),
                   em_median_disc = median(simulated_discharge_m3s),
                   em_var_disc    = var(simulated_discharge_m3s))

emergence_tri <- disch_tri %>%
  dplyr::filter(doy >= unique(em_period$start_doy),
                doy <= unique(em_period$end_doy)) %>%
  dplyr::rename(cohort = year) %>%
  dplyr::group_by(cohort) %>%
  dplyr::summarise(em_mean_disc   = mean(simulated_discharge_m3s),
                   em_median_disc = median(simulated_discharge_m3s),
                   em_var_disc    = var(simulated_discharge_m3s))

ggarrange(
  ggplot(data = emergence_stj, aes(x = cohort, y = em_mean_disc)) +
    geom_point() + geom_line() + labs(title = "St-Jean River"),
  ggplot(data = emergence_tri, aes(x = cohort, y = em_mean_disc)) +
    geom_point() + geom_line() + labs(title = "Trinite River"),
  ncol = 2)

ggarrange(
  ggplot(data = emergence_stj, aes(x = cohort, y = em_median_disc)) +
    geom_point() + geom_line() + labs(title = "St-Jean River"),
  ggplot(data = emergence_tri, aes(x = cohort, y = em_median_disc)) +
    geom_point() + geom_line() + labs(title = "Trinite River"),
  ncol = 2)


# ── Yearly 75th-percentile discharge during emergence (Obedzinski et al. 2018) 

qt75_em_stj <- disch_stj %>%
  dplyr::filter(doy >= unique(em_period$start_doy),
                doy <= unique(em_period$end_doy)) %>%
  dplyr::group_by(year) %>%
  dplyr::summarise(
    em_quant_75qt_disc = as.numeric(quantile(simulated_discharge_m3s, 0.75))) %>%
  dplyr::rename(cohort = year)

qt75_em_tri <- disch_tri %>%
  dplyr::filter(doy >= unique(em_period$start_doy),
                doy <= unique(em_period$end_doy)) %>%
  dplyr::group_by(year) %>%
  dplyr::summarise(
    em_quant_75qt_disc = as.numeric(quantile(simulated_discharge_m3s, 0.75))) %>%
  dplyr::rename(cohort = year)

ggarrange(
  ggplot(data = qt75_em_stj, aes(x = cohort, y = em_quant_75qt_disc)) +
    geom_line() + labs(title = "St. Jean"),
  ggplot(data = qt75_em_tri, aes(x = cohort, y = em_quant_75qt_disc)) +
    geom_line() + labs(title = "Trinite"),
  ncol = 1)


# ── Cohort-weighted 75th-percentile discharge during growth (Obedzinski 2018) ─

qt75_gr_co_stj <- weighted_co_disch_75qt(
  smolt_data     = prop_smolt_sub_stj,
  discharge_data = disch_stj,
  periods        = gr_period_stj
) %>%
  rename(co_gr_mean_75qt_disc = co_mean_disch)

qt75_gr_co_tri <- weighted_co_disch_75qt(
  smolt_data     = prop_smolt_sub_tri,
  discharge_data = disch_tri,
  periods        = gr_period_tri
) %>%
  rename(co_gr_mean_75qt_disc = co_mean_disch)

ggarrange(
  ggplot(data = qt75_gr_co_stj, aes(x = cohort, y = co_gr_mean_75qt_disc)) +
    geom_line() + labs(title = "St. Jean"),
  ggplot(data = qt75_gr_co_tri, aes(x = cohort, y = co_gr_mean_75qt_disc)) +
    geom_line() + labs(title = "Trinite"),
  ncol = 1)


# ── Cohort-weighted minimum 30-day average discharge during growth ────────────

co_30d_mean_disch_stj <- weighted_co_disch_30d(
  smolt_data     = prop_smolt_sub_stj,
  discharge_data = disch_stj,
  periods        = gr_period_stj
)

co_30d_mean_disch_tri <- weighted_co_disch_30d(
  smolt_data     = prop_smolt_sub_tri,
  discharge_data = disch_tri,
  periods        = gr_period_tri
)

ggarrange(
  ggplot(data = co_30d_mean_disch_stj,
         aes(x = cohort, y = co_30d_mean_disch)) +
    geom_line() + labs(title = "St. Jean"),
  ggplot(data = co_30d_mean_disch_tri,
         aes(x = cohort, y = co_30d_mean_disch)) +
    geom_line() + labs(title = "Trinite"),
  ncol = 1)


# ── Export ────────────────────────────────────────────────────────────────────

# Merge all discharge metrics by cohort for each river, then combine
stj_all <- Reduce(
  function(x, y) merge(x, y, by = "cohort", all = TRUE),
  list(weighted_co_season_stj, emergence_stj, qt75_em_stj,
       qt75_gr_co_stj, co_30d_mean_disch_stj))

tri_all <- Reduce(
  function(x, y) merge(x, y, by = "cohort", all = TRUE),
  list(weighted_co_season_tri, emergence_tri, qt75_em_tri,
       qt75_gr_co_tri, co_30d_mean_disch_tri))

stj_all$river <- "stj"
tri_all$river <- "tri"

data_all <- bind_rows(stj_all, tri_all) %>%
  dplyr::select(river, cohort, everything())

write_fst(data_all,
          path = file.path(base_path,
                           "R/03_clean_data/River/River_Discharge.fst"))

